### ISSUE TITLE
Feature Request: Do not display "Failed Cluster Policies" when ui.views.clusterPolicyReports is set to false

### ISSUE THREAD

**Issue by windowsrefund** [fjogeleit/policy-reporter#100]
Seems this would make sense.

**Comment by fjogeleit** [comment]
Hey thanks for your request. I implemented it a bit different. I separated the dashboard configuration from the view configuration.

https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/charts/ui/values.yaml#L116

You can set `ui.views.dashboard.clusterPolicyReports` to `false`. This will disable all clusterpolicy information from the dashboard. Same works with PolicyReports.

This feature was released as v2.2.0 of the Helm Chart
