### ISSUE TITLE
`capabilities.drop["all"]` is case sensitive and triggers existing kyverno policy

### ISSUE THREAD

**Issue by skuethe** [fjogeleit/policy-reporter#112]
Hey there,

first off, thank you for this helpful tool. Makes adapting kyverno even easier.

I was "quick starting" kyverno and stumbled upon this issue, that the existing (strict) kyverno policy `disallow-capabilities-strict` will trigger on the `policy-reporter` deployment.

The problem:
The policy is testing upper case "ALL" as necessary drop capability:
https://github.com/kyverno/policies/blob/b3d81ea30e8751a503abe9dd888cc6cc3d4ebd72/pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml#L39-L41

All deployment templates in this repo use a lower case "all" and therefor trigger the policy.

I first tried adding a `to_upper` function on that `validate` `condition`, but that just got messy, because we are already in a `foreach` loop for the containers.

Although I was unable to find a definition from Kubernetes side if a lower case "all" is allowed, all references I could find just adapt the upper case solution.
So I am going the easy way first and will add a PR here that fixes it for `policy-reporter`.

**Comment by fjogeleit** [comment]
Thanks for your contribution and your great feedback.

**Comment by fjogeleit** [comment]
I released your fix with version v2.2.6 of the Helm Chart
