### ISSUE TITLE
Additional labels for Loki target

### ISSUE THREAD

**Issue by praveen-livspace** [fjogeleit/policy-reporter#117]
In a multi cluster environment, we have one policy-reporter (PR) running in each cluster. Each PR server sends the events to a central Loki server. It will be useful to specify additional Loki labels in the PR config to query and create alerts on events from different PR servers separately.

**Comment by fjogeleit** [comment]
Hey, thanks for your request. This makes sense and I will have a look on this.

**Comment by fjogeleit** [comment]
Custom Loki labels are available with the Helm Chart version 2.4

See https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml#L149 for reference or https://kyverno.github.io/policy-reporter/guide/04-helm-chart-core#enable-targets--notification for an example
