### ISSUE TITLE
Policy-Reporter-UI behind a rancher reverse proxy  Error 403

### ISSUE THREAD

**Issue by fschwarm24** [fjogeleit/policy-reporter#122]
Is there a way to reach the UI internally via rancher without an ingress? I can access the web interface, but I don't get any data displayed.
The problem is the following:
example URL in rachner:
https: //rancher.com/k8s/clusters/xyz/api/v1/namespaces/policy-reporter/services/http:policy-reporter-ui:8080/proxy/

Request of the UI:
https: //rancher.com/api/ 
instead of 
https: //rancher.com/k8s/clusters/xyz/api/v1/namespaces/policy-reporter/services/http:policy-reporter-ui:8080/proxy/api

Or is there a solution for the user login? Then the policy-reporter can also be accessible from outside.

**Comment by fjogeleit** [comment]
Hey, thanks for your request. I will try it on my rancher cluster if I can get it working or if I can provide some configuration to get it working

**Comment by fjogeleit** [comment]
I build a new version of Policy Reporter UI which supports sub path URLs and works with the rancher proxy.

I will release a new version of the helm chart next week but you can already try it out by changing the Policy Reporter UI Version in your values yaml:

```yaml
ui:
  enabled: true
  image:
    tag: 1.3.2
```

**Comment by fschwarm24** [comment]
Yeah it works. Thank you very much for the quick support.

**Comment by fjogeleit** [comment]
Nice to hear, thanks for your feedback
