### ISSUE TITLE
Grafana Dashboard PolicyReports panel columns need updating

### ISSUE THREAD

**Issue by Boojapho** [fjogeleit/policy-reporter#123]
I'm using the Grafana dashboard named `PolicyReports` provided in the Helm chart.  To be consistent with other dashboards, the panel columns should be updated as follows:

`Failing PolicyRules`
- Add `category` and `severity` columns in front of `namespace`

`Failing ClusterPolicyRules`
- Filter out `Pass` and `Skip` statuses since this is supposed to be for failing policies only
- Reorder columns to be inline with other dashboards (`category`, `severity`, `kind`, `name`, `policy`, `rule`, `status`)
- Remove `container` column

**Comment by fjogeleit** [comment]
Hey thanks for your suggestions, I will have a look on it.
