### ISSUE TITLE
Add drop-down filtering to top of `PolicyReports` dashboards

### ISSUE THREAD

**Issue by Boojapho** [fjogeleit/policy-reporter#124]
On both of the "Details" dashboards included in the Helm Chart, there are drop-down filters at the top for `Policy`, `Category`, `Severity`, `Namespace` (PolicyReport Details only) and `Kind`.  I'd like to see these same filters on the `PolicyReports` dashboard.

**Comment by fjogeleit** [comment]
I will have a look on this as well

**Comment by fjogeleit** [comment]
With the HelmChart v2.6.1 you should get the new filters for the PolicyReports Dashboard as well as the new columns and fixed order of existing columns
