### ISSUE TITLE
Prometheus metric labels not matching what Kyverno emits

### ISSUE THREAD

**Issue by alen-z** [fjogeleit/policy-reporter#127]
Hi,

Prometheus metrics do not contain validation mode label (audit or enforce) so we are not able to filter by this setting.

Potential solutions:
1. Additional validation mode label in Policy Reporter `policy_report_result` metric is available.
2. Enabled `relabelings` in `ServiceMonitor` so we can conform Policy Reporter label names to Kyverno naming and then we can use Prometheus metric joining based on the same label name to append validation mode data.

Using only Kyverno or Policy Reporter metrics is not a silver bullet. They are different. Kyverno shows validation mode when Policy Reporter does not, Policy Reporter shows name of the resource affected when Kyverno does not etc.

What do you think?

**Comment by fjogeleit** [comment]
Hey, thanks for your suggestions.

This sounds reasonable.

> 1. Additional validation mode label in Policy Reporter policy_report_result metric is available.

This option doesn't work well. I know that Policy Reporter is mainly used with Kyverno but not limited to it. So I can only process information that are part of the PolicyReport CRD.

> 2. Enabled relabelings in ServiceMonitor so we can conform Policy Reporter label names to Kyverno naming and then we can use Prometheus metric joining based on the same label name to append validation mode data.

So you mean `relabelings` as part of the possible configuration values in the Helm Chart? That should be possible.

Thanks for this ideas.

**Comment by fjogeleit** [comment]
The latest version of the helm chart has new configurations in the values yaml to configure relabeling:

https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/charts/monitoring/values.yaml#L10

let me know if you still need support to reach your goal.

**Comment by alen-z** [comment]
Nice! I just thought I'll use a bit of my time today to create a PR for this, but you were faster :) On to upgrade to `2.6.2`. Appreciate it. Enjoy the weekend.

**Comment by fjogeleit** [comment]
Great, thanks for considering and much fun and success.

Thanks you too
