### ISSUE TITLE
Allow to show only (kyverno) policy reports from specific namespaces

### ISSUE THREAD

**Issue by stieglma** [fjogeleit/policy-reporter#131]
## What

It would be great to have a config option in the helm chart to filter of which namespaces policy-reports should be shown

## Why
We have a multi-tenant cluster with a single kyverno instance. The policies are all the same for everyone. Now it would be very cool if I could give different teams on the cluster access to different deployments of policy-reporter, where they can only see their individual reports, and not everything from all other teams, too.

## How

Ideally this config option allows to configure:
- a list of namespaces
- the namespaces can contain wildcards, such that `teamA-*` will mean that all policies reports from `teamA-namespace1`, `teamA-namespace2`, ... are shown
- all namespaces not following the list with the patterns should be ignored

**Comment by fjogeleit** [comment]
Thanks for your request. Sounds like a good improvement. I will have a look on it.

**Comment by fjogeleit** [comment]
ReportFilter are now available with v2.7.0. See https://kyverno.github.io/policy-reporter/core/09-report-filter/ for details. It supports include and exclude filter for namespaces. You can also disable clusterReports.

**Comment by stieglma** [comment]
works like a charm, thank you!

**Comment by fjogeleit** [comment]
Great, thanks for your feedback
