### ISSUE TITLE
http proxy error causing policy-reporter-ui slowness

### ISSUE THREAD

**Issue by yogeek** [fjogeleit/policy-reporter#147]
Our policy reporter UI regularly responds very slowly and sometimes an error message appears : `Unable to retrieve all Data from the Server`

In the logs :

```
2022/06/02 16:20:38 http: proxy error: context canceled
2022/06/02 16:20:44 http: proxy error: context canceled
2022/06/02 16:20:44 http: proxy error: context canceled
2022/06/02 16:20:44 http: proxy error: context canceled
```

When we update a kyverno policy, the information takes a long time to appear in the UI whereas the report CRD has already been updated.

Any idea about a configuration we can tune to improve this please ?

Additinnal notes :
- Version : chart v2.8.0
- We use policy reporter for kyverno reports only

**Comment by fjogeleit** [comment]
hey, thanks for your feedback. How big is your cluster? Or how many results kyverno creates across your namespaces ca?

I will release a new version in the next days with general performance improvements but would be good to know in which environments it has still performance issues.

I will also work out a serverside pagination, which also should help for bigger clusters.

**Comment by yogeek** [comment]
Hey @fjogeleit , thank you for your help.

The concerned cluster has autoscaler but is usually between 30 and 40 nodes (with about 100 namespaces, 600 deployments and 1400 pods)

We have 34 clusterpolicies that generated 80 policyreports

**Comment by fjogeleit** [comment]
Okay, thanks a lot for your inside. Thats indeed a big cluster.

As I mentioned I recently created 2 PRs. 
The first one added serverside pagination, this should improve the frontend performance significant.
The second one improves the concurrent processing of PolicyReport events which hopefully also helps with your problem.

Another possible solution would be to have multiple installations of policy-reporter. You can use the reportFilter configuration to process only a subset of namespaces for a single installation. Thats not ideal but could also help.

**Comment by fjogeleit** [comment]
Hey @yogeek I released v2.9.0 of the Helm Chart today. It brings the mentioned improvements in performance and memory usage. Please let me know if it helps with your issues or if there are still problems.

**Comment by yogeek** [comment]
Hey @fjogeleit ! thank you 👍 
We just upgrade it, I will keep you in touch regarding the performance.

**Comment by fjogeleit** [comment]
thanks a lot

**Comment by yogeek** [comment]
@fjogeleit I confirm that the new release seems to solve the issues we observed before.
I close this issue for now, thanks a lot for your help

**Comment by fjogeleit** [comment]
great, thank you very much for your feedback, it helped me a lot. Let me know if you encounter any other issue.
