### ISSUE TITLE
svg logo for policy-reporter

### ISSUE THREAD

**Issue by mirtov-alexey** [fjogeleit/policy-reporter#151]
Hello!
Iam from Yandex Cloud. Recently we contributed with yandex cloud s3 to policy reporter.
We want to add policy-reporter to our [Yandex Cloud Kubernetes Marketplace](https://cloud.yandex.com/en/marketplace?type=K8S) and we need the logo of policy-reporter in svg format.
I tryed to convert your [image](https://kyverno.github.io/policy-reporter/images/logo-light.png) from docs to svg but unfortunately i didnt meet a good quality and size. Could you pleasee send me your logo in svg format in normal quality and size?
Thank you very much

**Comment by fjogeleit** [comment]
Hey @mirtov-alexey thanks for your request. The Logo is the Kyverno logo which you can find here: https://github.com/kyverno/artwork with the Policy Reporter typeface. If you need it together I can check later if I can provide it together as SVG

**Comment by mirtov-alexey** [comment]
@fjogeleit Hello!
Thank you!
it would be really cool if you could provide the logotype together like in the example. If it’s really hard, then at least they provided a font so that we can glue the font and logo ourselves

**Comment by fjogeleit** [comment]
okay, let me check if I find the template / svg of the logo on my computer.

**Comment by fjogeleit** [comment]
Is this okay for you? It is not identical but the same font and colors. The Font is "DM Sans" regular if needed.

![Kyverno-Policy-Reporter](https://user-images.githubusercontent.com/16627596/173412388-79e28f7f-9cc7-4749-9c16-214ad8b279c8.png)

![Kyverno Policy Reporter](https://user-images.githubusercontent.com/16627596/173412990-2d3ff31a-e728-4b06-96f3-11b5005e9d08.svg)

**Comment by mirtov-alexey** [comment]
@fjogeleit Thank you very much

**Comment by fjogeleit** [comment]
Great, no problem. Thanks for adding Policy Reporter to your Marketplace,
