### ISSUE TITLE
Bad image tag in policy-reporter-ui in kyverno-policy-reporter-ui manifest

### ISSUE THREAD

**Issue by NovemberZulu** [fjogeleit/policy-reporter#152]
Right now policy-reporter-ui image tag in kyverno-policy-reporter-ui manifest is "4" ([link](https://github.com/kyverno/policy-reporter/blob/6040b8e0879a2f2dcd3eb7a3fc51dedf4e3fca9e/manifest/kyverno-policy-reporter-ui/install.yaml#L207)). I guess it should be 1.4.0, based on [default-policy-reporter-ui manifest](https://github.com/kyverno/policy-reporter/blob/6040b8e0879a2f2dcd3eb7a3fc51dedf4e3fca9e/manifest/default-policy-reporter-ui/install.yaml#L96)?

**Comment by fjogeleit** [comment]
oh sorry, yeah thats right, I will fix this asap

**Comment by fjogeleit** [comment]
Fixed, thanks for reporting
