### ISSUE TITLE
"1 shared_informer.go:401] The sharedIndexInformer has started, run more than once is not allowed" in logs

### ISSUE THREAD

**Issue by NovemberZulu** [fjogeleit/policy-reporter#163]
Hello! I see this line repeated in logs of Policy Reporter every five seconds or so:
> 1 shared_informer.go:401] The sharedIndexInformer has started, run more than once is not allowed

I have metrics server enabled with "--metrics-enabled", it seems to be somehow related. I can troubleshoot more if need be. Thank you!

Maxim

**Comment by fjogeleit** [comment]
Hey, which version do you running? I released this morning the helm chart version v2.9.5 which the newest policy-reporter version 2.6.2. This version should fix this issue.

**Comment by NovemberZulu** [comment]
My bad, I didn't mention the version -- I am using [policy-reporter-2.9.1](https://github.com/kyverno/policy-reporter/releases/tag/policy-reporter-2.9.1), let me try to update to the latest version. Thanks!

**Comment by NovemberZulu** [comment]
It helped! Thank you!
