### ISSUE TITLE
Policy reporter Grafana dashboards stopped working

### ISSUE THREAD

**Issue by mceronja** [fjogeleit/policy-reporter#168]
Hi!

So I have latest policy-reporter Helm chart (2.10.0) and I have the monitoring enabled.

```# Settings for the monitoring subchart
monitoring:
  enabled: true
  serviceMonitor:
    labels:
      release: kube-prometheus-stack
  plugins:
    kyverno: true
  grafana:
    # required: namespace of your Grafana installation
    namespace: monitoring-system
    dashboards:
      # Enable the deployment of grafana dashboards
      enabled: true
      # Label to find dashboards using the k8s sidecar
      label: grafana_dashboard
    folder:
      # Annotation to enable folder storage using the k8s sidecar
      annotation: grafana_folder
      # Grafana folder in which to store the dashboards
      name: Big Brother
```

What is interesting that these 3 Dashboards worked on Monday and I did no changes on the policy-reporter itself.
But what I did is a couple of kube-prometheus-stack Helm chart upgrades. I didn't see anything dangerous there, but my suspicion is that something changed that the policy-reporter is expecting.

On Monday I did upgrade from 36.2.1 -> 36.6.1 and 36.6.1 -> 36.6.2 (nothing special in values file)
On Wednesday 36.6.2 -> 37.0.0 (here they changed metricRelabelings and cAdvisorMetricRelabelings)
On Thursday  37.0.0 -> 37.2.0 (nothing special in values file)

Not sure when the dashboards stopped working, but they worked on Monday and yesterday after the upgrade I got this:

![pr1](https://user-images.githubusercontent.com/11294554/179185108-93e30534-9fc7-41b4-a61d-527c6c04195a.PNG)

![pr2](https://user-images.githubusercontent.com/11294554/179185161-88ac69be-d639-4117-8415-51f35e6eb031.PNG)

Or maybe I am on the wrong track here?

Thanks!

**Comment by fjogeleit** [comment]
Hey, thanks for the report, I will check an installation with the latest prometheus stack and check if anything changed

**Comment by fjogeleit** [comment]
In a fresh setup with the latest versions everything works as expected and I encounter no issues.

Are the Policy Reporter dashboards the only ones that are not working?

Can you check that your Prometheus still has Policy Reporter as working target configured.

**Comment by mceronja** [comment]
I checked several others and they all work including the Kyverno one: https://kyverno.io/docs/monitoring/bonus-grafana-dashboard/
Targets also seem ok:
![pr3](https://user-images.githubusercontent.com/11294554/179215498-a5ef5b4e-7e1b-4371-a28b-16c909ee08b3.PNG)

**Comment by fjogeleit** [comment]
Can you query the metrics over prometheus? Like `policy_report_result`

Not sure if it has problems with the data of your metrics, maybe some illegal character in the labels I am not aware of or the Dashboard Configurations. The error message is not really clear about it. Do you maybe see some more details in Grafana logs?

**Comment by fjogeleit** [comment]
One thing you could try is tu reinstall policy-reporter. I am not sure but maybe the upgrade introduced some issues with the Policy Reporter config maps that are managed by Policy Reporter Helm Chart.

I think the unexpected identifier issue comes from the empty value selections but I don't know why they are empty. The default should be `All`. Maybe this `Failed to call resource` is the reason but I can't say why it is failing.

**Comment by mceronja** [comment]
For policy_report_result I got -> Load time: 139ms   Resolution: 14s   Result series: **3081**
Basically I got alot of results.

This is from the grafana log after I try to open the dashboard:
```
level=error msg="Failed to call resource" error="query must contain metric name\n"
level=error msg="Request Completed" method=GET path=/api/datasources/2/resources/series status=500
```

**Comment by fjogeleit** [comment]
Do you get this error on the `PolicyReports` Dashboard? Do you get the same error for the `PolicyReports Details` Dashboard or another one?

**Comment by mceronja** [comment]
I did re-install nothing changed.
All 3 "Policy Reporter" Dashboards have the same behavior.

**Comment by fjogeleit** [comment]
hm okay, and they all have the same error log? `query must contain metric name`

**Comment by mceronja** [comment]
So it's like this:

**clusterpolicyreport-details**
```
level=error msg="Failed to call resource" error="parse error at line 1, col 1: syntax error: unexpected IDENTIFIER"
```

**policyreport-details**
```
level=error msg="Failed to call resource" error="parse error at line 1, col 1: syntax error: unexpected IDENTIFIER"
```

**policyreports**
```
level=error msg="Failed to call resource" error="query must contain metric name\n"
```

**Comment by fjogeleit** [comment]
Can oyu please try this Query in your prometheus and Grafana Explore:

`label_values({__name__=~ "policy_report_result|cluster_policy_report_result", status=~"fail|error"}, policy)`

On your details pages, do you have any possible selection for on of the filters? Like `All` or a concrete one.

**Comment by mceronja** [comment]
You mean these? Because it seems it can't find label_values? **EDIT: Aha this is only valid for templating?**

![p1](https://user-images.githubusercontent.com/11294554/179233142-27f13488-087b-4c87-b25a-3eee1cd9816a.PNG)

![g1](https://user-images.githubusercontent.com/11294554/179233313-4b15aab2-731b-40b7-912a-d58cc88bf21d.PNG)

If you check the first picture I sent you can see there are 0 filters available.

**Comment by fjogeleit** [comment]
Hm yeah, my fault you can not check query functions in the explorer...

It seams that the issues all are related to the Variables.

Can you go to the "Dashboard Settings" of one of the Dashboards and check under "Variables" if they are working or returning some issues. Seems that the queries may not work for any reason.

**Comment by mceronja** [comment]
Could it be the data source maybe?
What is the data source for all of this?

I have 2 data sources in Grafana. Loki (default) and Prometheus. 
When I edit a variable I see the datasource is Loki?

When I check the config maps with the dashboard json I see `"datasource": "-- Grafana --"`

**Comment by fjogeleit** [comment]
Hm could be, can you just try another one. In my case it uses Prometheus as source

**Comment by mceronja** [comment]
```
cat cluster-policy-reporter-details-dashboard.json | grep '"datasource":'
        "datasource": "-- Grafana --",

cat policy-reporter-details-dashboard.json | grep '"datasource":'
        "datasource": "-- Grafana --",

cat policy-reporter-dashboard.json | grep '"datasource":'
        "datasource": "-- Grafana --",
    "datasource": null,
    "datasource": null,
    "datasource": null,
    "datasource": null,
    "datasource": null,
```

This is from the json files on the Grafana pod.

When I edit a variable the datasource it set to Loki and I can't update it without an error. When I change data source to Prometheus and add the same Query I can update it with no problem.

So I guess the data source is the problem, but why did this start happening? And what should we do about it?

**Comment by fjogeleit** [comment]
I will create a new version of the Helm Chart with a new value for the datasource. Why this started now I don’t know but then you can simply change the source via the helm chart

**Comment by mceronja** [comment]
Yeah very strange... I can't remember was Loki always the default data source...

But this is definitely wrong right?
```
      "targets": [
        {
          "datasource": {
            "type": "loki",
            "uid": "P8E80F9AEF21F6940"
          },
          "expr": "sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", status=\"pass\"})",
          "instant": true,
          "interval": "",
          "legendFormat": "",
          "refId": "A"
        }
      ],
```
This is just a snippet from one of the dashboards.

**Comment by fjogeleit** [comment]
yes, it should be Prometheus

```json
        "datasource": {
          "type": "prometheus",
          "uid": "prometheus"
        }
```

Thats how it looks like in my environment. I think because it is not declared in the ConfigMap it falls back to the default, Loki in your case.

**Comment by mceronja** [comment]
I checked these dashboards because they have different data sources as a good example: https://github.com/fluxcd/flux2/tree/main/manifests/monitoring/monitoring-config/dashboards

The dashboards work, the Prometheus ones and Loki ones.

So as you said maybe it would be good if this could be altered via the Helm chart? Because currently my only option is to change the default data source, but that might break something else...

**Comment by mceronja** [comment]
Also here is the Kyverno dashboard which works:
https://kyverno.io/docs/monitoring/bonus-grafana-dashboard/

it uses **DS_PROMETHEUS_KYVERNO** variable which is set to **prometheus**

**Comment by fjogeleit** [comment]
I will have a look and reach back as soon as I have a fixed version. Thanks for your help so far

**Comment by fjogeleit** [comment]
@mceronja I released v2.10.1 with a fixed monitoring subchart. Prometheus should now be your default datasource and you have a new select to change it.

Let me know if it works or if you still have issues.

**Comment by mceronja** [comment]
@fjogeleit upgraded to 2.10.1 and it works.

Thanks for the help!

**Comment by fjogeleit** [comment]
Great, thanks for your feedback
