### ISSUE TITLE
[FR] Implement PodDisruptionBudget in the charts of the policy-reporter package

### ISSUE THREAD

**Issue by pierluigilenoci** [fjogeleit/policy-reporter#174]
The Kyverno package already has the PDBs implemented in the chart but not for the policy-reporter packages.

**Comment by fjogeleit** [comment]
Thanks for your request, I will have a look on it

**Comment by pierluigilenoci** [comment]
@fjogeleit thank you!

**Comment by fjogeleit** [comment]
At the first look I am not sure if it is currently useful to add PDBs for the Core App and KyvernoPlugin. 

Kyverno implements PDBs for the HA mode, which makes sense but PolicyReporter does not support HA mode (replicaCount > 1) for the Core App and KyvernoPlugin yet.

Maybe I would have to tackle this first before I can add this feature.

**Comment by fjogeleit** [comment]
The new Helm Chart Release v2.11.0 supports HA mode for each component. I will update the documentation soon. The new Helm Chart also adds PDBs for each component that runs with a replicaCount > 1

**Comment by pierluigilenoci** [comment]
@fjogeleit thanks so much!

**Comment by fjogeleit** [comment]
you're welcome. Please let me know if you encounter any issue
