### ISSUE TITLE
MS Teams Notification Allow Skip TLS

### ISSUE THREAD

**Issue by qgervacio** [fjogeleit/policy-reporter#176]
Hi Kyverno Team,

Looking at https://raw.githubusercontent.com/kyverno/policy-reporter/main/charts/policy-reporter/values.yaml, possible to add skipTLS for MS Teams notifications?

<img width="960" alt="Screenshot 2022-07-25 at 3 29 38 PM" src="https://user-images.githubusercontent.com/8968331/180722239-dd4046ff-25df-43b8-a54f-31e0fdf150d7.png">

Thank you

**Comment by fjogeleit** [comment]
hey @qgervacio, thanks for your request. I will have a look on it

**Comment by fjogeleit** [comment]
With the latest Helm Chart v2.11.0 the MS Teams configuration supports the new `target.teams.skipTLS` configuration which is `false` by default.
