### ISSUE TITLE
Additional clusters behind proxy doesn't work

### ISSUE THREAD

**Issue by rgeraskin** [fjogeleit/policy-reporter#177]
Trying to use an amazing feature from #167 I noticed that external clusters behind reverse proxy can't been accessed. E.g. my external policy-reporter is accessed through an nginx ingress.

The reason [is ](https://pkg.go.dev/net/http/httputil#NewSingleHostReverseProxy)
> NewSingleHostReverseProxy does not rewrite the Host header. To rewrite Host headers, use ReverseProxy directly with a custom Director policy.

Requests to the ingress controller are submitted with wrong Host header and root policy-reporter can't gather the data. So only non-proxied setups work for now.

**Comment by fjogeleit** [comment]
Hey, thanks for your issue. I will check it out.

**Comment by fjogeleit** [comment]
I updated the ReverseProxy to also overwrite the request host correctly and add the `X-Forwarded-Host` and `X-Origin-Host` header.

I released the version of the UI as v1.6.1

You can try it out by overwriting the Tag in the Helm Values:

```yaml
ui:
  image:
    tag: 1.6.1
```

Please let me know if it is working or you still encounter any issues. I will release a new Chart version with this fix next week.

**Comment by rgeraskin** [comment]
I've tried it, works like a charm! Thank you
