### ISSUE TITLE
Summary and violation reports dont generate logs

### ISSUE THREAD

**Issue by MaxRink** [fjogeleit/policy-reporter#179]
Ive tested both the summary and violations report feature of the helm chart, but both dont produce logs.
In my case, i only got the summary email but no violation email, although both jobs are marked as recieved.
it would be nice if the jobs could output what they are working on

**Comment by fjogeleit** [comment]
Hey, thanks for your feedback. I will have a look on it this week. So the summary email worked but not the violation one? But both CronJobs were created? And both generated a Job which were successful?

but yes I will add some logs to get better insides.

**Comment by fjogeleit** [comment]
I prepared [v2.8.1-dev](https://github.com/kyverno/policy-reporter/tree/v2.8.1-dev) with some more info logs.

Can you maybe check if there are some information that helps you?

You can use it with:

```yaml
image:
  tag: 2.8.1-dev
```

**Comment by fjogeleit** [comment]
Hey @MaxRink, just want to ask if you where able to get it work or if you tried the additional logging version.

**Comment by fjogeleit** [comment]
Closed because of inactivity, feel free to reopen if you still have issues
