### ISSUE TITLE
Update default policy-reporter version in example values.yaml

### ISSUE THREAD

**Issue by awhitepl** [fjogeleit/policy-reporter#192]
This file https://raw.githubusercontent.com/kyverno/policy-reporter/main/charts/policy-reporter/values.yaml

Sorry I don't have time for a PR.

**Comment by fjogeleit** [comment]
Not sure what you mean. Main has the v2.9.0 App version set which was build today. But it’s not released yet. The new helm chart will be released tomorrow

**Comment by fjogeleit** [comment]
I released the new Helm Chart Version https://github.com/kyverno/policy-reporter/releases/tag/policy-reporter-2.12.0 with the latest version of the App
