### ISSUE TITLE
Send data to slack (perhaps other targets) even if validationFailureAction=enforce

### ISSUE THREAD

**Issue by cherez0ff** [fjogeleit/policy-reporter#195]
Is it possible to configure policy-reporter so that it sends to slack failed (by kyverno) attempts to create a resource? If validationFailureAction is "audit" - then data being sent to slack, if validationFailureAction is "enforce" - it does not.
If it is not possible to configure it that way now - please make such feature

Script to check this behavior
```bash
minikube start --kubernetes-version=v1.24.2 --driver=virtualbox --cpus=8

helm repo add kyverno https://kyverno.github.io/kyverno/
helm repo update
helm install kyverno --namespace kyverno kyverno/kyverno --create-namespace 
helm install kyverno-policies --namespace kyverno kyverno/kyverno-policies --set validationFailureAction=enforce
helm install policy-reporter --namespace kyverno policy-reporter/policy-reporter --set target.slack.webhook="$SLACK_WEBHOOK"  

git clone https://github.com/BishopFox/badPods.git
kubectl apply -f badPods/manifests/priv/deamonset/priv-exec-deamonset.yaml -n default
# No data has been sent to slack since "validationFailureAction=enforce"
```

**Comment by fjogeleit** [comment]
It's already possible with the BlockReports feature of the Policy Reporter Kyverno Plugin. This feature creates policyreports for enforce policy checks based on the Kubernetes Events.

You can check the documentation for details: https://kyverno.github.io/policy-reporter/guide/helm-chart-core#enable-enforce-violation-policyreports-requires-kyverno--170
