### ISSUE TITLE
Slack Webhook Should Come From Secret

### ISSUE THREAD

**Issue by hi-artem** [fjogeleit/policy-reporter#198]
According to[ Slack docs](https://api.slack.com/messaging/webhooks#getting_started):

> Keep it secret, keep it safe. Your webhook URL contains a secret. Don't share it online, including via public version control repositories. Slack actively searches out and revokes leaked secrets.

The policy-reporter should allow for Webhook to be populated from k8s secret (using secret reference) so that consumers using Git to store application state can safely configure the Helm Chart.

**Comment by fjogeleit** [comment]
Thanks for your issue, I am currently planning this kind of functionality but it's a bit tricky because of the channel support, which makes the amount of configured Webhooks dynamic. I will have a deeper look into this in the upcoming weeks.

**Comment by hi-artem** [comment]
@fjogeleit Yea that makes sense. 

I also noticed that similar is true for S3, or basically any other resource added in future that would require authentication (for example PagerDuty).

**Comment by fjogeleit** [comment]
Yes, when I implement such a feature I would do it for all targets

**Comment by hi-artem** [comment]
Awesome! Thank you

**Comment by fjogeleit** [comment]
I implemented a first version of a possible solution.

It adds a new config to each target called `secretRef`. It can be used to configure an already existing secret and picks up, depending on the target, the Host, Webhook, Username, Password, Token, AccessKeyID and/or SecretAccessKey. You can also set a different secret on each channel of an target.

Token is a bit special and dedicated for the Webhook Target. It will set as Authorization header to the request and should help to support secure authentication against protected endpoints.

The key should be a mapping to the related configuration in the target. Like `webhook` for the Slack `webhook` value.

Current limitations:

* The secret has to exist when Policy Reporter starts, if the secret not exist, the target will be skipped.
* Policy Reporter does not recognize when the Secret changes or is replaced. It only reads the values once.

**Comment by fjogeleit** [comment]
I released this feature today with v2.13.0
