### ISSUE TITLE
Pod don't have common labels

### ISSUE THREAD

**Issue by ademar59** [fjogeleit/policy-reporter#201]
In your helm chart, you define common labels.

All manifests use it.
In deployment too, but not in spec : 
https://github.com/kyverno/policy-reporter/blob/fbea49797c6d2928c3108a1d10e57e791ce54cb3/charts/policy-reporter/templates/deployment.yaml#L24

**Comment by fjogeleit** [comment]
What's your use case for this labels? I am working with the deployment more often.

**Comment by ademar59** [comment]
We use metrics for pod (runtime) not for deployment

**Comment by ademar59** [comment]
Labels are converted to tag of our metrics

**Comment by fjogeleit** [comment]
okay, what additional labels do you need or miss?

```
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/part-of: {{ include "policyreporter.name" . }}
```

or also

```
app.kubernetes.io/component: reporting
app.kubernetes.io/managed-by: {{ .Release.Service }}
```

?

**Comment by ademar59** [comment]
at least for example

    app.kubernetes.io/version: 2.9.0
    helm.sh/chart: policy-reporter-2.12.0

**Comment by fjogeleit** [comment]
I added this labels also on a pod level and will release it next week
