### ISSUE TITLE
Add option to add certificate for taget(s)

### ISSUE THREAD

**Issue by cherez0ff** [fjogeleit/policy-reporter#205]
I have an issue with certificate when trying to use internal elastic server as target to send errors with policy-reporter

```
(k logs pod/***-policy-reporter-b9756956d-j9x4n)
2022/09/16 12:40:44 [ERROR] Elasticsearch PUSH failed: Post "https://***:9260/sec-kyverno-2022.09.16/event": x509: certificate signed by unknown authority
```
Can you please add an option to add custom CA certificate(s)?

**Comment by fjogeleit** [comment]
With the PR I created, you are able to add your cert as volume and configure the path as RootCA for your target. Would this work for you?

**Comment by fjogeleit** [comment]
I released v2.13.0 of the helm chart with the new certificate config for most outputs including elasticsearch

**Comment by cherez0ff** [comment]
Hi! This does not seem to work for me. Was this tested?
Does not work if I set "certificate" as a path to a mounted cert file from configmap, nor if I just set "skipTLS: true"

Logs of pod:
2022/09/23 11:46:51 [ERROR] Elasticsearch PUSH failed: Post "https://***/sec-kyverno-2022.09.23/event": x509: certificate signed by unknown authority

My cert is ok - I confirmed it with curl on same server

**Comment by fjogeleit** [comment]
I was not able to test it because I have elasticsearch with custom cert setup.

So you mounted your cert secret as volume in the container and then configured the path in the certificate property right?

**Comment by cherez0ff** [comment]
Hell, sorry, my bad!
I used same helm values config with only adding new parameters, so I didn't change image versions. I will fix as soon as I can to confirm everything works

**Comment by cherez0ff** [comment]
2022/09/24 09:41:20 [INFO] Elasticsearch PUSH OK

All good

**Comment by fjogeleit** [comment]
Ah Great, thanks a lot for your feedback
