### ISSUE TITLE
Kyverno Plugin 1.42 not available

### ISSUE THREAD

**Issue by dschunack** [fjogeleit/policy-reporter#207]
Hi,

the AppVersion of the Kyverno Plugin was changed yesterday, but no image is available in the registry.

https://github.com/kyverno/policy-reporter/commit/e3dcd8e92092c721b47eaaa712b0fa59f9168bdf

Update to the latest release of the policy report failed.
Latest available version is [v1.4.1](https://github.com/orgs/kyverno/packages/container/package/policy-reporter-kyverno-plugin).

Please, build a new Image or revert the Commit.

```yaml
  Warning  Failed     42m (x4 over 44m)      kubelet            Failed to pull image "ghcr.io/kyverno/policy-reporter-kyverno-plugin:1.4.2": rpc error: code = Unknown desc = Error response from daemon: manifest unknown
 ```

**Comment by fjogeleit** [comment]
sorry, I will check that

**Comment by fjogeleit** [comment]
The build is running and should be available in half an hour. Thanks for reporting.
