### ISSUE TITLE
Export policy violations to AWS Security Hub

### ISSUE THREAD

**Issue by pealtrufo** [fjogeleit/policy-reporter#209]
Hi,

I am exploring ways to export policy violations to AWS Security Hub. Is this something you've considered as part of this project? Are you aware of any other approach to achieve that? 

Thanks!

**Comment by fjogeleit** [comment]
Hey, because I don't use AWS I am not aware of this tool. Do you have an API or something to consider? Then I am happy to have a look on it and how to implement it as new target.

**Comment by pealtrufo** [comment]
Hey @fjogeleit, there's this link to Security Hub API reference: https://docs.aws.amazon.com/securityhub/1.0/APIReference/Welcome.html

I am not very familiar with it either myself. I've seen [Trivy](https://github.com/aquasecurity/trivy) does support integration with Security Hub, and what they do is generating a report with format ASFF, which then can be pushed to Security Hub
https://github.com/aquasecurity/trivy/blob/main/docs/tutorials/integrations/aws-security-hub.md

**Comment by fjogeleit** [comment]
thanks, I will check it in the upcoming weeks and if there is a good way to integrate it

**Comment by fjogeleit** [comment]
First draft of the AWS securityhub integration. Its a new target which pushes new results to the security hub via the AWS SDK

<img width="1558" alt="Bildschirm­foto 2023-04-09 um 16 40 50" src="https://user-images.githubusercontent.com/16627596/230779395-23c714a5-096f-4e4e-83f3-f0face12ebe7.png">
<img width="595" alt="Bildschirm­foto 2023-04-09 um 16 41 04" src="https://user-images.githubusercontent.com/16627596/230779399-04a2b2ad-3ac9-4cec-b93c-b7b45dad4ed5.png">
<img width="835" alt="Bildschirm­foto 2023-04-09 um 16 41 23" src="https://user-images.githubusercontent.com/16627596/230779400-e91b3ff5-e370-483e-9397-440452ea6f0f.png">
