### ISSUE TITLE
[FR] move helm chart repo to kyverno

### ISSUE THREAD

**Issue by Hokwang** [fjogeleit/policy-reporter#212]
Hi,

I raised issue at kyverno/kyverno (https://github.com/kyverno/kyverno/issues/4136)
But think once again,
it is only policy-reporter problem.

how about use `kyverno/policy-reporter` for helm chart repo
like other component?

Thanks,

**Comment by fjogeleit** [comment]
With a central `chart` repository would this be possible but in the current situation it makes everything much more complicated for new releases.

So I keep it in mind but for now it will be as it is.

**Comment by treydock** [comment]
I don't think this is a reasonable change to make without some compelling reason besides having fewer Helm repos.  If there was some technical limitation fewer repos would solve, then that might be a compelling enough reason.  More explanations here: https://github.com/kyverno/kyverno/issues/4136#issuecomment-1792769095
