### ISSUE TITLE
Policy Report PDF Generation

### ISSUE THREAD

**Issue by dsxsh** [fjogeleit/policy-reporter#218]
The policy reporter can already generate a programmatic view, and/or a UI view for the policy statuses, but as a feature request I'd really love to see some level of PDF generation (or similar exec-friendly file type) to be able to easily generate "pretty pictures" of the policy reports through the clusters.

**Comment by fjogeleit** [comment]
Thanks for your request, what be an HTML report / representation also work for you? Like the HTML templates for the email reports?

What kind of information you would like to see?

**Comment by dsxsh** [comment]
I do think HTML generation would be okay, I could convert that to pdf fairly easily.

I guess my goal would be that I can show compliance for each policy dynamically piece by piece. So I can show a dev team compliance with their set of apps, and an exec compliance across the whole cluster. I think I'd want to see a mixed view, have a summary overview of just, 'Compliant with x rules', and a breakdown of compliance with each rule individually. Alternatively noncompliance as such, so that an exec can receive a total overview of every app and it's compliance.

**Comment by fjogeleit** [comment]
Okay,I understand the basic idea but it's not that easy of me to understand what kind of structure of the data would achieve your needs.

Example:

Shows the current E-Mail Report with the basic information about policy reports but if I understand your requirements right, you would need a more fine grained structure per App / Namespace / Policy ?

<img src="https://kyverno.github.io/policy-reporter/images/reports/violations-report.png" />

**Comment by dsxsh** [comment]
Honestly that looks great. But yeah I'd want to generate on a per namespace, and per policy basis. So that I can get a report for validations of a single policy across the entire cluster, single policy in a single namespace, all policies in a single namespace, and all policies in the entire cluster.

I don't know if I care about an "app", I think having just namespaced structures would be quite acceptable.

**Comment by fjogeleit** [comment]
Sorry for the late response. I think I got your requirements. I will work on prototype in the next weeks, as soon as I find some time. Would you like to have an API with different parameters to configure the report, (select namespaces, policies, grouped-by, etc) and/or an integration in the UI with the configuration and an "download" action?

**Comment by fjogeleit** [comment]
Current state of the reports

* Summary for results per Policy / Namespace / Rule
* Details about the status of each resources per namespace

<img width="953" alt="report-details-1" src="https://user-images.githubusercontent.com/16627596/205918287-c4964b7f-9445-4629-b31b-88e0391a2865.png">

<img width="945" alt="report-details-2" src="https://user-images.githubusercontent.com/16627596/205918300-5b99cefd-adad-41b4-8f0a-b22fe4e0757a.png">

**Comment by fjogeleit** [comment]
The new HTML Reports are released with Helm Version v2.14.0
