### ISSUE TITLE
[Target s3] Allow path style access

### ISSUE THREAD

**Issue by oliver-creed** [fjogeleit/policy-reporter#225]
Hi,

I would like to use path style access with the s3 Target is there a way to enable this, can't see any configuration currently that allows is there a way to implement this as a config change for the s3 target?

**Comment by fjogeleit** [comment]
Hey, I will have a look and add a configuration if possible.

**Comment by fjogeleit** [comment]
I released 2.13.5 of the Helm Chart with a new `pathStyle` bool option for the S3 target. It will enforce the PathStyle in the SDK. Let me know if its not working as expected.
