### ISSUE TITLE
[UI, Helm] Support for ingress

### ISSUE THREAD

**Issue by samip5** [fjogeleit/policy-reporter#227]
I would like to see the helm chart to support ingress too, which seems it doesn't currently include.

**Comment by fjogeleit** [comment]
Ingress support is already available, see https://kyverno.github.io/policy-reporter/guide/helm-chart-core#ingress for details.

**Comment by samip5** [comment]
Must have missed that somehow, my bad. :)

**Comment by fjogeleit** [comment]
No problem, let me know if you encounter any issue
