### ISSUE TITLE
[Bug] Multiple replicas unable to send reports to MSTeams

### ISSUE THREAD

**Issue by JuanPabloSGU** [fjogeleit/policy-reporter#228]
### Bug

It seems like when having multiple replicas of policy-reporter and having the target set to teams, it seems that no results are sent to teams. 

### Environment 
* policy-reporter (chart) - 2.13.5 
* helm - version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}
* Microsoft Teams - 1.5.00.31168

### Steps To Reproduce

Change replicaCount to greater than 1 and target is set to teams.

### Expected Behaviour

Pods should be able to send results with a replicaCount greater than 1. 

#### When the replicaCount is set to 3.
![image](https://user-images.githubusercontent.com/71339561/204622682-b6686418-7b43-45fc-a1c2-53bbef5cea65.png)

#### When the replicaCount is set to 1. 
![image](https://user-images.githubusercontent.com/71339561/204622964-02834a3b-0813-448b-af35-dc11ec002ef4.png)

### Additional Notes

This could be specific issue with just Teams but would be helpful testing other targets if it is a target wide issue.

**Comment by fjogeleit** [comment]
Thanks for reporting, I will have a look

**Comment by fjogeleit** [comment]
I tried to reproduce your issue but the behavior was as expected:

I had 3 Pods of Policy Reporter and created a nginx pod which violated some PSS Policies -> triggered messages in MS Teams

Then I deleted the current leader pod which is the only pod that sends messages

Then after a new leader was elected I created another nginx pod which triggered again some messages.

-------------

The basic flow is that only the leader can send messages, to ensure that no message is send multiple times and a new leader only sends messages for violations which happened after the leader was elected.

**Comment by JuanPabloSGU** [comment]
Thank you for testing! I can agree that it is working now that the reports have been sent out. I am not sure the reason for the delay in messages. We did configure it to have only one pod running to get most of the backlog of reports to be sent and then transition to having more replicas.

**Comment by fjogeleit** [comment]
And you have still performance issues? And if - do you have a general time frame how long the delay is?

**Comment by JuanPabloSGU** [comment]
There doesn't seem to have any performance issues. Currently we have three pods deployed, I guess that the issue resolved itself.

**Comment by fjogeleit** [comment]
Okay, so I will close the issue. Let me know if you encounter any other problem.
