### ISSUE TITLE
Support Ingresses natively in chart

### ISSUE THREAD

**Issue by knechtionscoding** [fjogeleit/policy-reporter#232]
Having an `ingress.enabled` plus labeling, annotations, and options for ingressclass would be helpful to natively support exposing policy-reporter via an ingress.

**Comment by knechtionscoding** [comment]
@fjogeleit Happy to submit a PR that adds this functionality to the chart if you'd like. If this isn't something you want to support we can also just close this out.

**Comment by fjogeleit** [comment]
Hey @KnechtionsCoding, an ingress comfiguration for the UI is already available, see https://kyverno.github.io/policy-reporter/guide/helm-chart-core#ingress for details.

**Comment by knechtionscoding** [comment]
Then ignore me! Thanks! Sorry, not sure how i missed that in the documentation!

**Comment by fjogeleit** [comment]
You're welcome. Thanks for your request anyway.
