### ISSUE TITLE
Documentation request: add version buttons of Helm Chart versions

### ISSUE THREAD

**Issue by awhitepl** [fjogeleit/policy-reporter#264]
I would like to request similar style helm chart version numbers that Kyverno repo project does on this repo so that version numbers are viewable at a glance as illustrated in this image:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/104788427/219425573-8bbdf9d1-ec90-4483-b2d4-757eea193c49.png">

**Comment by fjogeleit** [comment]
hey, thanks for your request. I will have a look on it.

**Comment by fjogeleit** [comment]
I added the badges but the Helm Chart is already prepared for the next release, so they currently not reflect the latest currently release.

**Comment by fjogeleit** [comment]
Available with the latest release infos (v2.17.0)
