### ISSUE TITLE
Add Ingress Helm templates for policy-reporter and Kyverno plugin

### ISSUE THREAD

**Issue by Balsir** [fjogeleit/policy-reporter#274]
Hello, we run policy-reporter in multiple clusters and view all policy reports via a central UI.

We currently have to create custom Ingress resources for policy-reporter and Kyverno plugin in the external clusters, so that UI can reach them. It would be awesome if the Helm chart supported creation of these Ingresses out of the box, similarly to how UI has it.

Would it please be possible to add Ingress templates for policy-reporter and Kyverno plugin into the Helm chart?

**Comment by fjogeleit** [comment]
hey, thanks for your request.

I will add templates for both components in the next release, thanks for mentioning. It didn't make sense before the external cluster feature, but you are right that there is a use case for it now.

**Comment by Balsir** [comment]
Cool, thank you :)

**Comment by fjogeleit** [comment]
@Balsir the new ingress templates for the KyvernoPlugin and Core App are released today with v2.18.0

**Comment by Balsir** [comment]
Thank you, works like a charm!
