### ISSUE TITLE
[Chart] Policy Reporter ServiceMonitor Missing Namespace Selector

### ISSUE THREAD

**Issue by aballman** [fjogeleit/policy-reporter#283]
The template here allows you to specify a different namespace for the service monitor. 
https://github.com/kyverno/policy-reporter/blob/bc7d8fbea65cb9a61afe192f7f3c7783a361489b/charts/policy-reporter/charts/monitoring/templates/servicemonitor.yaml#L5

The `monitoring.smNamespace` helper allows you to specify a namespace other than the `.Release.Namespace` or `.Values.global.namespace`

https://github.com/kyverno/policy-reporter/blob/bc7d8fbea65cb9a61afe192f7f3c7783a361489b/charts/policy-reporter/charts/monitoring/templates/_helpers.tpl#L61-L69 

The problem being that if you do specify a different namespace than the release namespace, the service monitor will be missing a`namespaceSelector` in the spec that's a requirement if the serviceMonitor isn't in the same namespace as the service/endpoint
https://github.com/kyverno/policy-reporter/blob/bc7d8fbea65cb9a61afe192f7f3c7783a361489b/charts/policy-reporter/charts/monitoring/templates/servicemonitor.yaml#L15-L34

This issue prevents prometheus from scraping the metrics endpoint

**Comment by fjogeleit** [comment]
Hey, thanks for reporting. I will have a look on it

**Comment by L1ghtman2k** [comment]
@fjogeleit How would one apply this to kyverno plugin's service monitor?

**Comment by fjogeleit** [comment]
@L1ghtman2k  there is a dedicated value for the plugin service monitor within the monitoring subchart

https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/charts/monitoring/values.yaml#L33

**Comment by L1ghtman2k** [comment]
> @L1ghtman2k there is a dedicated value for the plugin service monitor within the monitoring subchart
> 
> https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/charts/monitoring/values.yaml#L33

Oh, i see, I was looking for something in the values.yaml  that contains "plugin". Makes sense now, thanks!
