### ISSUE TITLE
[core] Slack notification

### ISSUE THREAD

**Issue by yuriydzobak** [fjogeleit/policy-reporter#284]
Hi,
Thanks for nice app
It would be nice to support slack notification per channel.
Right now you have to create webhook per each channel and then configure filter, etc. 
Slack supported webhook that can send msg in any cahnnel, so in this case you can have only single webhook then change destination slack channel -> https://api.slack.com/messaging/webhooks#oauth_response

As you have https://github.com/kyverno/policy-reporter/blob/61d883dad1f4e4333ea544eea143167dcb3e3e20/pkg/target/slack/slack.go
For example,To add an option to configure the channel for Slack in the `slack.client` code, you can add a new field to the client  struct to hold the channel name or ID, and then include this field in the Slack webhook payload.  Here's an example of how to modify the `slack.client` code to include a configurable channel: 
```go
 type client struct {
	target.BaseClient
	webhook      string
	client       http.Client
	customFields map[string]string
	channel      string // new field for channel name or ID
}

func (s *client) newPayload(result report.Result) payload {
	p := payload{
		Attachments: make([]attachment, 0, 1),
		// include the channel name or ID in the payload
		Channel: s.channel,
	}

	// rest of the code remains the same
	// ...
}

func NewClient(name, host string, skipExistingOnStartup bool, filter *report.ResultFilter, httpClient http.Client, customFields map[string]string, channel string) target.Client {
	return &client{
		target.NewBaseClient(name, skipExistingOnStartup, filter),
		host,
		httpClient,
		customFields,
		channel, // initialize the new field with the channel name or ID
	}
}
```
When creating a new `slack.client`, pass the channel name or ID as an argument to the `NewClient()` function.
But need to improve helm chart, doc, read configmap, etc

**Comment by fjogeleit** [comment]
Hey, thanks for this suggestion. I will have a look on it.

**Comment by fjogeleit** [comment]
The latest release has channel support with the new „channel“ property. If you define multiple slack targets the sub target inherit the webhook from the root slack target if not specified. So you only need to configure the webhook ones and only change the slack channel.
