### ISSUE TITLE
[bug] Upgrade from 2.11.0 -> 2.11.1 causes errors with Istio fronting the service

### ISSUE THREAD

**Issue by diranged** [fjogeleit/policy-reporter#288]
Hi! We're trying to upgrade from 2.11.0 -> 2.18.x (.0 and .1 tried), and while the UI comes up, we find that we can't data from the "Dashboard", "Policy Reports" or "Cluster Policy Reports" pages. We only get valid data from the "Kyverno Policies" page.

The other pages all report the same error just like this:
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/768067/229146962-606ab9ba-cea0-4cf9-8760-0283a4b315f3.png">

You can see in the dev console that we're getting `502`s back.. and no matter what we try in the Helm chart config, we can't get any verbose logging that would indicate where the problem is. Any suggestions on where to look?

**Comment by diranged** [comment]
Updated ... the issue is in https://github.com/kyverno/policy-reporter-ui/pull/158/files. We're exposing the Kyverno UI pod via Istio. The upgrade from `2.11.0` -> `2.11.1` is where the failure begins for us. I believe https://github.com/kyverno/policy-reporter-ui/pull/158/files is the root cause, but don't yet understand why it causes the failure.

**Comment by fjogeleit** [comment]
Hey, with 2.18.0 a new value for the ui subchart is available to get debug logs of the proxy requests: https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/charts/ui/values.yaml#L75

I could provide a config to switch to a simple proxy without the forward headers if this doesn’t work in your setup

**Comment by fjogeleit** [comment]
Should be fixed in v2.18.2 by setting `ui.api.overwriteHost` to `false`.
