### ISSUE TITLE
Allow searching through contained words

### ISSUE THREAD

**Issue by jemag** [fjogeleit/policy-reporter#299]
Currently it seems that we can search by the first word of a given column, for example here with `falcoui` we get:
![image](https://user-images.githubusercontent.com/7985687/232105444-d2cfef94-c75c-4fd6-b025-8fe117ac0857.png)
However, if searching for a string that is contained not at the beginning, we will not get any result:
![image](https://user-images.githubusercontent.com/7985687/232105536-7ae77664-7a49-4d2a-8d28-aa090e08ee2a.png)

It would be nice to be able to search using any string contained within any column. For example, in my case, I have a lot of workloads containing oauthproxy, but none are at the beginning:
![image](https://user-images.githubusercontent.com/7985687/232106187-3a1a979d-8c1c-4fe2-9bc1-617654920313.png)
So currently I have to search these individually, instead of being able to get them all using the string `oauth`

Overall this could be as simple as checking if it contains the search string, but even better could be doing a fuzzy search ([FZF-style](https://github.com/junegunn/fzf))

**Comment by fjogeleit** [comment]
Hey, I will have a look on it

**Comment by fjogeleit** [comment]
I added support to search within some fields like resource name, policy etc. I left out improvements in the UI for now. I plan a rewrite / restructuring of the UI. I will keep the search improvement for this purpose in mind.

**Comment by fjogeleit** [comment]
Released with v2.19.0 of the Helm Chart
