### ISSUE TITLE
Wrong image in manifest/policy-reporter-kyverno-ui/install.yaml 

### ISSUE THREAD

**Issue by ledroide** [fjogeleit/policy-reporter#301]
https://github.com/kyverno/policy-reporter/blob/332f7be8e16f2ed442a87bca9ac430ce596880dc/manifest/policy-reporter-kyverno-ui/install.yaml#L161

`image: "ghcr.io/kyverno/policy-reporter-ui:1.5.1"` does not exist.

Same deployment for HA variant podSpec : ` image: "ghcr.io/kyverno/policy-reporter-kyverno-plugin:1.5.1"` 

https://github.com/kyverno/policy-reporter/blob/332f7be8e16f2ed442a87bca9ac430ce596880dc/manifest/policy-reporter-kyverno-ui-ha/install.yaml#L241

I confirm that changing to ` image: "ghcr.io/kyverno/policy-reporter-kyverno-plugin:1.5.1"`  in the first link/manifest fixes the issue.

**Comment by fjogeleit** [comment]
Hey, thanks for reporting. I will fix this today

**Comment by fjogeleit** [comment]
Fixed the image in the related install.yaml
