### ISSUE TITLE
Unable to import policyreport/v1alpha2

### ISSUE THREAD

**Issue by nikolay-o** [fjogeleit/policy-reporter#302]
Hello @fjogeleit , I want to use structure `v1alpha2.PolicyReportResult` in my project, but it turns out I can't import package `github.com/kyverno/policy-reporter/blob/main/pkg/crd/api/policyreport/v1alpha2`

I tried to use it using following snippet
```
go mod init test
go get github.com/kyverno/policy-reporter/blob/main/pkg/crd/api/policyreport/v1alpha2
```

and got error
```
go: downloading github.com/kyverno/policy-reporter v1.10.3

go: module github.com/kyverno/policy-reporter@upgrade found (v1.10.3), but does not contain package github.com/kyverno/policy-reporter/blob/main/pkg/crd/api/policyreport/v1alpha2`
```

I think that is because tags are not following semver, wdyt, is it possible to cope this issue?

**Comment by fjogeleit** [comment]
Hey, for this issue I would recommend to have a look on https://github.com/kubernetes-sigs/wg-policy-prototypes/tree/master/policy-report/pkg which is intended to import it in other projects

**Comment by nikolay-o** [comment]
thanks a lot, will try it!
