### ISSUE TITLE
policy_report_result{} should include type of policy

### ISSUE THREAD

**Issue by L1ghtman2k** [fjogeleit/policy-reporter#303]
policy_report_result{} metric should include type of a policy. (ClusterPolicy vs Policy). Otherwise, there might be issues when ClusterPolicy and Policy have the same name.

For instance, with this metric (exported under "simple" mode):
```
policy_report_result{category="Best Practices, EKS Best Practices", endpoint="http", exported_namespace="calico-apiserver", instance="policy-reporter", job="policy-reporter", namespace="policy-reporter", policy="broken-cluster-policy-deployment", severity="medium", source="kyverno", status="error"}
```

I can't tell if this is referring to clusterpolicy named `broken-cluster-policy-deployment`, or the policy with the same name

**Comment by fjogeleit** [comment]
Hey, thanks for mentioning, I will have a look on it

**Comment by fjogeleit** [comment]
unfortunately I am not able to add the type of the Policy because I just have no information about it. The entire source of the metrics are (Cluster)PolicyReports, which don't have any information if the policy was a ClusterPolicy or Policy.

While PolicyReporter is mostly but not exclusively used with kyverno, I cannot include kyverno-specific information to remain independent of it.

**Comment by L1ghtman2k** [comment]
Don't the policy report names include a prefix to indicate the type? (I haven't tried the regular policies, but) clusterpolicy reports are prefixed with "cpol-"

**Comment by fjogeleit** [comment]
Yes but the type of the PolicyReport is not related to the type of Policy, its related to the validated resource. So if you create a ClusterPolicy that validates a namespaced resource like Pods, Deployments, Services, etc. it creates a PolicyReport in the related namespace of the resources. If you create a Policy that valides a cluster scoped resource, it will create a ClusterPolicyReport (e.g. for Namespaces, ClusterRoles, etc.)
