### ISSUE TITLE
Publish policy-reporter as OCI chart

### ISSUE THREAD

**Issue by MaxRink** [fjogeleit/policy-reporter#307]
Currently the policy-reporter isn't published as an OCI chart like kyverno is.
Ideally the policy-reporte  chart also gets published to ghcr.io

**Comment by fjogeleit** [comment]
Thanks for your request, I will have a look

**Comment by fjogeleit** [comment]
The latest release is now also available as OCI. I will adopt this for all coming releases.

https://github.com/kyverno/policy-reporter/pkgs/container/charts%2Fpolicy-reporter

**Comment by MaxRink** [comment]
@fjogeleit that didnt seem to work for 2.19.1 and .2

**Comment by fjogeleit** [comment]
@MaxRinkv 2.19.2 should be available now
