### ISSUE TITLE
provide policy validationFailureAction in policy_report_result metric for the reports

### ISSUE THREAD

**Issue by riuvshyn** [fjogeleit/policy-reporter#312]
Hello, I've noticed that `validationFailureAction` is missing in `policy_report_result` metric which is making the whole project unusable for to some extend.
I wanted to use this project to fire alerts for reports which were failed policies with `validationFailureAction: Enforce`.

**Comment by fjogeleit** [comment]
hey @riuvshyn,

`validationFailureAction` is not part of the PolicyReport CRD, so its not possible to add it to the metrics because its a kyverno specific value.

So your use case is to observe if an already existing manifest violates an enforced policy? Because Kyverno only produces policy reports for existing resources which violates an enforce policy when background scanning is enabled for this policy.

**Comment by riuvshyn** [comment]
@fjogeleit Hello,
Yeah I do have validation for manifests that's gating everything from being applied that fails policies. 
However sometimes new policies are introduced and  existing resources in cluster might  fail new policy but usually first you introduce new policy in `Audit` mode to evaluate the impact so I don't want to trigger alerts on these reports...
I understand that `validationFailureAction` is a policy specific thing but I thought maybe there is some way to get and provide that info because we know exactly what policy failed.

**Comment by fjogeleit** [comment]
hm there is not really something I can do right now. All information I can process are based on the PolicyReport, no Kyverno policy crd.

So as long it's not part of the report, I have no way to add it to the metrics. One thing that would be possible is to add the action type as label to the report, this is something policy reporter supports as metric label source, unfortunately does kyverno currently not allow to add custom labels to reports, there is an issue (https://github.com/kyverno/kyverno/issues/5542) for that but I don't see any other way right now.

**Comment by riuvshyn** [comment]
Oh, yeah custom labels would be great! 
I understand now and agree there is not much todo for policy-reporter.
Thanks!

**Comment by fjogeleit** [comment]
Thanks too, I will see if I can tackle the issue to make this functionality happen
