### ISSUE TITLE
falco adapter integration didn't generate any reports 

### ISSUE THREAD

**Issue by tprakash17** [fjogeleit/policy-reporter#318]
used these instructions to do the integration - https://github.com/kubernetes-sigs/wg-policy-prototypes/tree/master/policy-report/falco-adapter.  we are able to successfully use trivy adapter https://github.com/fjogeleit/trivy-operator-polr-adapter 

`--set falcosidekick.policyreport.enabled=true --set falcosidekick.policyreport.failthreshold=3 --set falcosidekick.policyreport.maxevents=10`
@fjogeleit

**Comment by fjogeleit** [comment]
As discussed is the generation of the reports handled by Falcosidekick. Nothing I can do here.
