### ISSUE TITLE
UI name confusion

### ISSUE THREAD

**Issue by EsDmitrii** [fjogeleit/policy-reporter#321]
Hi!
I have some Cluster Policies for Kyverno.
When I open UI I see this:
ClusterPolicy Reports tab is empty
<img width="1726" alt="Screenshot 2023-06-19 at 21 45 06" src="https://github.com/kyverno/policy-reporter/assets/124890665/b80c554a-a2ad-43a2-b4a0-21d1a0215887">

But Policy Reports tab has of data
<img width="1727" alt="Screenshot 2023-06-19 at 21 46 02" src="https://github.com/kyverno/policy-reporter/assets/124890665/0fc4c24f-62d8-4a06-a483-b93943d3fba8">

Also on Dashboard tab there is 0 Failing Cluster Policies, but they're exist
<img width="1728" alt="Screenshot 2023-06-19 at 21 49 29" src="https://github.com/kyverno/policy-reporter/assets/124890665/4ddb1f29-6b23-476b-add9-57d7241d67e6">

And the last one, this button doesn't work
<img width="91" alt="Screenshot 2023-06-19 at 21 50 48" src="https://github.com/kyverno/policy-reporter/assets/124890665/ac19e760-6e12-435d-a1ff-f57d3fe3df6b">

Installed by Helm, chart version: 2.19.2

**Comment by fjogeleit** [comment]
Hey, the behavior is correct, you misunderstood the relation to cluster policies and cluster policy reports.

ClusterPolicyReports are created for results related to cluster scoped resources like namespaces, clusterroles, nodes, etc.

if a cluster policy validates namespaced resources like deployments, pods, etc. It will create policy reports in the related namespaces - no cluster policy reports
