### ISSUE TITLE
Gspace as Target Notification.

### ISSUE THREAD

**Issue by vikastharyani** [fjogeleit/policy-reporter#333]
Hello Community members!

Could you also add Google Space as a target notification?

**Comment by JimBugwadia** [comment]
Are you referring to Google Spaces (https://en.wikipedia.org/wiki/Google_Spaces)?

This seems to be discontinued.

**Comment by vikastharyani** [comment]
So we have channels in Slack, which we call spaces in Google Chat. Sorry for the confusion.

https://developers.google.com/chat/how-tos/webhooks

**Comment by fjogeleit** [comment]
If you use slack in the end, would it be an option to use the slack integration?

**Comment by vikastharyani** [comment]
> If you use slack in the end, would it be an option to use the slack integration?

Nope, we don't use Slack.

**Comment by fjogeleit** [comment]
Okay, then I misunderstood your comment. I will have a look but it can take some time.

**Comment by fjogeleit** [comment]
Will be available in the next release, end of the week
