### ISSUE TITLE
Adding Login to Policy-reporter UI screen

### ISSUE THREAD

**Issue by ProboticsX** [fjogeleit/policy-reporter#334]
Hi,
I needed to know if there's any way to implement a logon screen/any authentication method for the policy reporter UI?

**Comment by fjogeleit** [comment]
Hey, right now not. If you access it over an ingress you could add a basic auth mechanism.

there is an open issue #221 to implement authentication via openID but I don’t now when I find time to start with this.

**Comment by ProboticsX** [comment]
Thanks for the hint, will check it out!

**Comment by fjogeleit** [comment]
I close it as duplicate to #221
