### ISSUE TITLE
[Core] Grouped Notifications

### ISSUE THREAD

**Issue by galfrylich** [fjogeleit/policy-reporter#335]
Hey is there any chance to group the report so i dont get a bunch of messages to slack, like summery group by image 
or do it on the ui to group by image ?

**Comment by fjogeleit** [comment]
Grouping via Slack is not really possible. To see a grouped view, I would suggest using the UI, but grouping by resource is not currently available, but I could add it there.

**Comment by galfrylich** [comment]
thank you for the response, any chance to send alert to slack when new report is scan only with a link to the ui maybe ?

**Comment by fjogeleit** [comment]
You mean if different new results for a single resource are created, you want a single notification? Basically the same issue as implementing a single notification.

I would need to wait with the sending an result and wait for other findings with the same resource. I could have a look but it will take time. So no nearby solution for this.

**Comment by galfrylich** [comment]
thank you for your help, i will appreciate if you add it to your tickets

**Comment by fjogeleit** [comment]
As feature for the upcoming major release I am started working the general support for targets and a first implementation for Slack.

Any feedback is welcome.

<img width="610" alt="slack_group_notification" src="https://github.com/kyverno/policy-reporter/assets/16627596/934e4997-d000-4c3d-b9c6-c7fb709b7596">
