### ISSUE TITLE
Add cluster context in Slack notification

### ISSUE THREAD

**Issue by nsagnett** [fjogeleit/policy-reporter#339]
Hi there,

We have multi-cluster setup and we want to deploy kyverno with policy reporter on each one.
But, to distinguish involved cluster, we need have this information on Slack notification.

Is it possible to add it?

Many thanks

**Comment by fjogeleit** [comment]
Hey @nsagnett, all targets, including Slack have a `customFields` property which is a map of static information which will be added to each notification.

You can use this to add the clusterName to your slack messages.

**Comment by nsagnett** [comment]
Nice! Thank you!
