### ISSUE TITLE
Namespace is always kyverno in exported metrics + adding rule to grafana dashboard filtering

### ISSUE THREAD

**Issue by doryer** [fjogeleit/policy-reporter#340]
I've started to use the policy reporter metrics for Kyverno and I faced some issues I would like to raise:

1. As I see, for each pass/fail row in the Grafana dashboard table, the namespace is always `Kyverno`, I would like it to present the namespace of the kind of report
2. Also, suggestion is to add another variable in default for the Grafana dashboard which is `rule`, Clusters will probably have more than 1 rule so filtering on rules can be very useful
3. Another thing regarding rule, I've noticed I see in the metrics 2 rules, one is "rule" and the second is "autogen-rule", I see that autogen rule is coming from ClusterPolicy status. Still, I'm not sure why it is being exported in the metrics as it is causing duplication.

**Comment by fjogeleit** [comment]
You have to check the „exported_namespace“. Just namespace is set by Prometheus and relates to the namespaces of the policy reporter pod.

you can change this by setting honorLabels to true: https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/charts/monitoring/values.yaml#L12

policy reporter does not process clusterpolicies. Autogen rules are created and applied by kyverno and produces policy report results. If you don’t want autogen rules or results it’s up to your policy configuration.

If you want a rule filter in the dashboards you can simply add `rule` in the labelFilter value:

https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/charts/monitoring/values.yaml#L52

**Comment by doryer** [comment]
@fjogeleit Thank you very much i will try those
