### ISSUE TITLE
Grafana Dashboard is outdated

### ISSUE THREAD

**Issue by truongnht** [fjogeleit/policy-reporter#351]
In our cluster, we use AMP and AMG and not MonitoringStack. We saw that the [dashboards](https://grafana.com/grafana/dashboards/13995-policyreport-details) on Grafana Labs have been outdated. Is it possible to replace with latest version you have for MonitoringStack?

**Comment by fjogeleit** [comment]
Hey, thanks for mentioning. I will update them.

**Comment by truongnht** [comment]
hi @fjogeleit, since we would need the dashboard for our release. Do you have any estimation on when it can be updated? Thanks in advance 🙏🏼

**Comment by fjogeleit** [comment]
Today or tomorrow, sorry had a bussy week

**Comment by fjogeleit** [comment]
I updated all 3 templates to the current state. Let me know if you encounter any issue.

**Comment by truongnht** [comment]
Thank @fjogeleit for the help

**Comment by truongnht** [comment]
Hi @fjogeleit, 

While checking the updated dashboards vs what we have for Monitoring stack, I still see some differences 
* on PolicyReport details:
![image](https://github.com/kyverno/policy-reporter/assets/3480830/c2186434-8eb1-431a-9bca-dba049081efa)
vs 
![image](https://github.com/kyverno/policy-reporter/assets/3480830/051e6fd8-507d-4155-a6e3-0446d5bdb28b)
* on PolicyReports:
![image](https://github.com/kyverno/policy-reporter/assets/3480830/04405653-6976-4668-885d-0447c1f2bc62)
vs
![image](https://github.com/kyverno/policy-reporter/assets/3480830/79063211-b75d-48c5-a7d0-34d27e1a414f)

we donot have Cluster policy reports to compare. Is it possible for you to recheck on this?

**Comment by fjogeleit** [comment]
Have your metrics a `exported_namespace` or `namespace` label?

In the dashboards of the helm chart I use the `exported_namespace` label because the prom stack renames this label by default. In the uploaded Dashboards I use `namespace`. The original name of the label.

You can set `monitoring.serviceMonitor.honorLabels` to `true` in the Helm Chart to enforce the ServiceMonitor to use `namespace` as label.

**Comment by truongnht** [comment]
let me try that option

**Comment by truongnht** [comment]
you are right, @fjogeleit . Thanks for pointing out

**Comment by fjogeleit** [comment]
Sure, you're welcome.
