### ISSUE TITLE
Static manifest uses policy-reporter-ui:1.9.1, however 1.9.0 is the latest in GitHub packages

### ISSUE THREAD

**Issue by rigzba21** [fjogeleit/policy-reporter#354]
The [Static Manifest installation docs](https://kyverno.github.io/policy-reporter/guide/getting-started#core-policy-reporter-ui) `https://raw.githubusercontent.com/kyverno/policy-reporter/main/manifest/policy-reporter-ui/install.yaml` [references `policy-reporter-ui:1.9.1` ](https://github.com/kyverno/policy-reporter/blob/fd08aae0224d9b7164fbc8716796b6fb5d220ec9/manifest/policy-reporter-ui/install.yaml#L168), however, it appears that `1.9.1` is [not available in GitHub packages](https://github.com/orgs/kyverno/packages/container/policy-reporter-ui/versions?filters%5Bversion_type%5D=tagged), and I'm getting an `ErrImagePull` for `ghcr.io/kyverno/policy-reporter-ui:1.9.1`. Any help would be appreciated; thanks!

**Comment by fjogeleit** [comment]
Hey, sorry. I did not recognize that the image build failed. The missing tag should be available soon.

**Comment by fjogeleit** [comment]
The tag is now available

**Comment by rigzba21** [comment]
Excellent, thank you 🥳!
