### ISSUE TITLE
Huge memory consumption increase in reports-controller since upgrade to policy-reporter-2.21.0

### ISSUE THREAD

**Issue by bakito** [fjogeleit/policy-reporter#355]
Since I updated from 2.20.1 to 2.21.0 I see a huge increase in memory consumption of reports-controller.

With 2.20.1 a memory max of 194Mi was sufficient. With 2.21.0 the reports controller suddenly needs at least 1Gi memory.

What could be the issue here?

Kyverno Version: 3.0.5
With 25 Cluster Policies in place.

**Comment by bakito** [comment]
Sorry, the information was not correct.

**Comment by fjogeleit** [comment]
Hey, you mean the reports-controller from Kyverno? This has no relation.
