### ISSUE TITLE
Operation not permitted (Seccomp Profile Problem)

### ISSUE THREAD

**Issue by M-A-X-I-M** [fjogeleit/policy-reporter#358]
kyverno-policy-reporter container will get **CrashLoopBackOff**

log of container:
`runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abortPC=0x2124beb m=0 sigcode=18446744073709551610
goroutine 0 [idle]:runtime: g 0: unknown pc 0x2124beb`

**Comment by M-A-X-I-M** [comment]
After I changed the seccompProfile: type: from **RuntimeDefault** to **Unconfined** container ist starting and running.
Please check this, why it's from now on needed to be unconfined to running. This is not good for the security reason's.

**Comment by fjogeleit** [comment]
Which Kubernetes version / provider do you use?

**Comment by M-A-X-I-M** [comment]
OPEN TELEKOM CLOUD
K8s Rev: v1.25.3-r0-25.2.19

**Comment by fjogeleit** [comment]
My findings so far is that your image runtime / libseccomp are outdated.

> Newer base OS's use newer system calls and an older libseccomp can block them since they are unknown to it.

So theres nothing I can improve

**Comment by M-A-X-I-M** [comment]
Okay, we will check our EulerOS in the OTC for this Cluster. 
Because we don't get the same error in another Cluster where the EulerOS is higher.
Will report.

**Comment by fjogeleit** [comment]
Any updates, can the issue be closed?
