### ISSUE TITLE
[Helm] Ingress refers policy-reporter service, not UI service

### ISSUE THREAD

**Issue by tratsevsky** [fjogeleit/policy-reporter#360]
Hi,
I've deployed the policy-reporter with built-in UI via a helm chart with ingress enabled.
After deployment I see that ingress refers core service as a backend instead of ui service (e.g. there is a 'policy-reporter' service, not 'policy-reporter-ui' service), which causes error 404.
The template ingress.yaml seems like statically assigning the value to $fullName.
Is there existing way to make ingress working?

**Comment by fjogeleit** [comment]
Hey, you have an ingress config on root level which is for the core component and mainly for a multi cluster setup.

You also have an ingress config under the `ui` subchart for Policy Reporter UI

https://kyverno.github.io/policy-reporter/guide/helm-chart-core#ingress-1
