### ISSUE TITLE
Policy Reporter no longer working post kyverno 1.11.0 upgrade

### ISSUE THREAD

**Issue by rsavage-nozominetworks** [fjogeleit/policy-reporter#364]
This issue is being created to inform the developer community that post kyverno 1.11.0 upgrade, the Policy Reporter is no longer functioning properly.

Per a conversation in the Kybernetes/Kyverno slack channel:

@eddycharly mentioned: "Reports storage change quite a bit, cc @fjogeleit"

Here is an example screen shot of the effected policy reporter post 1.11.0 update: (If you noticed the Passed results are not displaying properly).   This is just one example.

![Policy_Reporter](https://github.com/kyverno/policy-reporter/assets/108539282/e4ce6354-5066-40b0-9000-9030ba3dae91)

**Comment by fjogeleit** [comment]
Will be fixed in app `v2.1.72`
