### ISSUE TITLE
Releases vs container image tag vs Helm Chart

### ISSUE THREAD

**Issue by balonik** [fjogeleit/policy-reporter#365]
Hi,

Latest release in GitHub is 2.21.1, latest image tag is 2.17.1 and appVersion in Helm Chart is 2.17.0.

How does it work? Will we get newer container tags please?

**Comment by fjogeleit** [comment]
I released a new container version which is not released via Helm Chart. I will release it soon.

the policy-reporter-* tag is always the latest helm chart version, not the latest app version.

**Comment by eloo-abi** [comment]
@fjogeleit is this really closed?

according to the CHANGELOG.md and github releases there is no version 2.17.2 of the kyverno-reporter

but the "current" docker image is version 2.17.2

so there are no release notes now and we its pretty hard to determine what changes are going to be deployed now. 

it looks like the version are misaligned a bit right now.. 
maybe 2.17.2 would match the 2.21.2 changelog?

**Comment by balonik** [comment]
I agree with @eloo-abi  on this one. CHANGELOG.md contains non Helm chart related changes so it is not true that anything after 2.17.0 was just Helm Chart changes. To me it seems that Policy reporter source code contains changes which are not properly released. The 2.17.2 tag just makes everything even worse..

**Comment by fjogeleit** [comment]
The current flow is t he following:

* Changelog contains changes between Helm Releases
* In regular follows a new Helm Release after a new app release was done

This case was an exception where I did an urgent fix before I released v2.17.1 via Helm.

Means all changes between v2.17.0 and v2.17.2 are listed in the latest Changelog entry.

Because the project is based on currently 3 different apps, (core, UI and plugin), I handled the complete changelog via the central Helm release which contains the changes for all components.

**Comment by eloo-abi** [comment]
@fjogeleit ah okay..
so maybe it would be useful to have the components versions as well in the changelog? 
so one can see that the current release (helm version) matches the following image versions?

**Comment by fjogeleit** [comment]
I’ll will try to improve the documentation in the changelog. I was thinking about adding the related app versions to the listing of changes to the components and a *next entry at the top with upcoming app version and changes.

**Comment by eloo-abi** [comment]
![image](https://github.com/kyverno/policy-reporter/assets/49561925/96494405-3bae-4ec6-b674-c755bc752842)

@fjogeleit i like that 👍

**Comment by balonik** [comment]
@fjogeleit thank you! ❤️

**Comment by fjogeleit** [comment]
Yep, thanks for your feedback
