### ISSUE TITLE
Allow excluding passed policy reports for Slack notifications.

### ISSUE THREAD

**Issue by bryanhorstmann** [fjogeleit/policy-reporter#370]
Thank you for this amazing tool.

When using the slack notifier, it would be great if it were possible to filter based on `Status`. It appears the only options (according to [the docs](https://kyverno.github.io/policy-reporter/core/targets#filter-since-appversion-250)) are `namespaces`, `policies` and `priorities`.

Ideally, I'd like to be notified in a Slack when a failure occurs but would like to exclude all`status: pass` to have a less noisy Slack channel.

Is something like this possible?

**Comment by fjogeleit** [comment]
Hey, thanks for the feedback. For this you can use https://kyverno.github.io/policy-reporter/core/targets#minimumpriority

As mentioned under https://kyverno.github.io/policy-reporter/core/priority-mapping pass results always have a info priority, so a minimumPriority of `warning` should only send fail results.

**Comment by bryanhorstmann** [comment]
Thats awesome! Thank you for the super quick feedback. I completely missed that.

**Comment by fjogeleit** [comment]
You're welcome. It was an early feature, thats because it has a dedicated option and not appears under the filter section.
