### ISSUE TITLE
Policy Reporter UI still displaying incorrect Passing vs Failing policy results after 2.21.2 update

### ISSUE THREAD

**Issue by rsavage-nozominetworks** [fjogeleit/policy-reporter#371]
The current policy reporter [2.21.2](https://github.com/kyverno/policy-reporter/releases/tag/policy-reporter-2.21.2) is still displaying inaccurate Policy results for `passing` vs `failed` policies.

### _***Versions***_

Kyverno Version: [v1.11.0](https://github.com/kyverno/kyverno/releases/tag/v1.11.0)
Policy Reporter: [2.21.2](https://github.com/kyverno/policy-reporter/releases/tag/policy-reporter-2.21.2)
Kubernetes Version: `1.28`

### _***Problem Summary***_

As you can see in the screenshot below, there are `122` Passed results, and `8` failed results.  However, the subsequent Failing Policy Reports listing and Passing Policy Reports listing do not accurately reflect the same counts.  

### _***Efforts to remedy***_

I have done various such as removing these policies, dropping the background scan reports, admission reports, and policy reports, and allowing everything to rebuild.   The display top left and right numbers are accurate, but the individual listings are not including everything needed.  I know the data is there, because if I execute (for example):

```
kubectl get PolicyReports --all-namespaces -o json
```
I can see all of the accurate policy data.   This appears to be a UI issue.

![policy-reporter-post-update_a](https://github.com/kyverno/policy-reporter/assets/108539282/2a323212-c2b0-40bc-ba08-1387f37c33d5)

**Comment by fjogeleit** [comment]
thanks for sharing, I'll check

**Comment by fjogeleit** [comment]
Can you please try `v2.17.4` once the build is done? Maybe in around ~45mins

**Comment by rsavage-nozominetworks** [comment]
@fjogeleit sure I will try and report back.  Thanks!

**Comment by rsavage-nozominetworks** [comment]
Hi @fjogeleit version `v2.17.4` seems to be working well now!

**Comment by fjogeleit** [comment]
Will release it as [2.21.3](https://github.com/kyverno/policy-reporter/releases/tag/policy-reporter-2.21.3) today
