### ISSUE TITLE
[Bug] policy-reporter is unable to start with multi replicas 

### ISSUE THREAD

**Issue by aslafy-z** [fjogeleit/policy-reporter#375]
With the following settings, policy-reporter chart 2.21.3 never gets ready:
```
replicaCount: 2
rest:
  enabled: false
```

Logs:
```
[...]
informers not synced yet, waiting for k8s client to complete startup
informers not synced yet, waiting for k8s client to be up
informers not synced yet, waiting for k8s client to complete startup
informers not synced yet, waiting for k8s client to be up
informers not synced yet, waiting for k8s client to complete startup
informers not synced yet, waiting for k8s client to be up
```

Kyverno and the CRDs are installed in version v1.10.6

**Comment by fjogeleit** [comment]
thanks for reporting, I will have a look

**Comment by aslafy-z** [comment]
@fjogeleit Let me know if you need more details about my setup.

**Comment by fjogeleit** [comment]
In my local tests everything worked fine. Do you have some details about the environment?

* Provider
* K8s Version
* previous Policy Reporter, basically last working version you used.

**Comment by fjogeleit** [comment]
Let me know if you still encounter this issue.
