### ISSUE TITLE
Add capability to set environment variables to deployments

### ISSUE THREAD

**Issue by tengremlin** [fjogeleit/policy-reporter#377]
Hello 👋 
I wanted to deploy reporter to my cluster, but I've noticed that chart doesn't support setting your own environment variables to workloads. I need this feature so I can set `HTTPS_PROXY` and `NO_PROXY` vars. Would you please consider adding this option to your chart?
Thanks
DG

**Comment by fjogeleit** [comment]
hi, I'll have a look on it

**Comment by kbcbals** [comment]
@fjogeleit 
created the [PullRequest](https://github.com/kyverno/policy-reporter/pull/378) for the[ issue-377](https://github.com/kyverno/policy-reporter/issues/377). Would you be able to review it please ?

**Comment by fjogeleit** [comment]
Released with v2.21.4

**Comment by pachr** [comment]
Hello, Have you find a way to use HTTP_PROXY / HTTPS_PROXY / NO_PROXY as environment variables?

I've set up these environments variables in my container with `envVars: []`, but the container doesn't seem to take these variables into account. I still have a timeout when I try to reach out to the slack webhook api (My proxy has [hooks.slack.com](hooks.slack.com ) in the whitelist, other containers can reach this API)

**Comment by fjogeleit** [comment]
which version do you use? Maybe the config is not correctly implemented in the new helm chart

**Comment by pachr** [comment]
I'm using the helm chart version 3.0.0-rc.8, which one should I use?

**Comment by fjogeleit** [comment]
thats fine, I will take a look on the config

**Comment by fjogeleit** [comment]
I found something in the code I need to add to support your configuration. Will create a new version today you can test

**Comment by pachr** [comment]
Thanks a lot @fjogeleit I'll be testing that as soon as the new version is available, and I'll let you know

**Comment by fjogeleit** [comment]
YOu chould be able to update to the latest RC release with the fixed image

**Comment by pachr** [comment]
Perfect it works, awesome, thank you very much :+1: (with the helm chart version `3.0.0-rc.9`)

`1.7315104989908216e+09	info	Slack: PUSH OK`
