### ISSUE TITLE
Missing Ingress labels

### ISSUE THREAD

**Issue by jseiser** [fjogeleit/policy-reporter#391]
https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml#L112

We use these to control whether external-dns creates a record or not.  Its shown in the values, but doesnt exist on the label.

https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/templates/ingress.yaml#L21

**Comment by fjogeleit** [comment]
thanks for reporting, I'll take a look on it.

**Comment by fjogeleit** [comment]
Released with Chart Version `2.21.6`. Thanks for your contribution
