### ISSUE TITLE
Missing container images for latest relases

### ISSUE THREAD

**Issue by iusergii** [fjogeleit/policy-reporter#395]
The last image that I can find in **ghcr.io** registry has tag **2.17.5**.

**Comment by fjogeleit** [comment]
That’s the latest app version, for what version you are looking for?

**Comment by iusergii** [comment]
Isn't this the latest [policy-reporter-2.21.6](https://github.com/kyverno/policy-reporter/releases/tag/policy-reporter-2.21.6) ?

**Comment by fjogeleit** [comment]
This is the latest Helm Release, which uses the latest app version 2.17.5

**Comment by iusergii** [comment]
Am I understanding correctly that not all releases are push images to registry?

**Comment by fjogeleit** [comment]
Yes, this repo contains the helm charts as well as the core app. If there are fixes on other components or only the helm chart then I only create a new Helm Release and not a new container image.

All `policy-reporter-*` tags are helm releases
All `v*` tags are app releases

In the [Changelog](https://github.com/kyverno/policy-reporter/blob/main/CHANGELOG.md)

You find the Helm Releases and related bumped app versions of the components

**Comment by iusergii** [comment]
I see, thank you for clarification. 
Closing
