### ISSUE TITLE
Additional customization for integration fields 

### ISSUE THREAD

**Issue by vponoikoait** [fjogeleit/policy-reporter#397]
Hi! 

It would a nice addition to have option customize potentially static fields like 
https://github.com/kyverno/policy-reporter/blob/main/pkg/target/securityhub/securityhub.go#L63 
```
				Types:         []string{"Software and Configuration Checks"},
                                  ....
				ProductFields: map[string]string{
					"Product Name": "Policy Reporter",
```
Being not quite sure regarding other integrations, but for the Security Hub ( I am actually unsure if these can be different value ), but it would be nice to have option to customize these, so that on UI I would be able to see name of my K8s cluster, for example, or whether I would put to the configuration

**Comment by fjogeleit** [comment]
With the latest release the product name can be changed via:  `target.securityHub.productName`
