### ISSUE TITLE
AWS related services automatically fill in Account ID if IRSA

### ISSUE THREAD

**Issue by vponoikoait** [fjogeleit/policy-reporter#398]
Hi! 

It may be safe to assume that for AWS related resources, in case if IRSA is utilized, it should be safe to assume that current session AWS account is AWS account push to, unless stated opposite 
https://github.com/kyverno/policy-reporter/blob/main/pkg/target/securityhub/securityhub.go#L50
As currently it seems to be always required to be configured as a must
There would be also nice to have update for policy-reporter-docs on required fields to be highlighted in some manner, as it may create small confusion initially interacting with policy reporter. 

Thank you for your help!

**Comment by fjogeleit** [comment]
With the next release AccountID will be optional if IRSA is used.
