### ISSUE TITLE
Teams message date fomat

### ISSUE THREAD

**Issue by picklednewtons** [fjogeleit/policy-reporter#400]
Hello,
When sending messages to teams we are receiving the messages in MM/dd/yyyy format but would prefer dd/MM/yyyy. I could not find a way to configure and the wondered if the conversion from the RFC3339 was implicit:

https://github.com/kyverno/policy-reporter/blob/eab50c38a91aa4398d16ddefea0ef914e10a5ff4/pkg/target/teams/teams.go#L97

Would be good to know if this is possible.

Many thanks.

**Comment by fjogeleit** [comment]
Hey, I'll take a look. Your proposed format makes also for me more sense.

**Comment by fjogeleit** [comment]
Hey, I just checked the code and the actual Format is "2006-01-02T15:04:05Z07:00". The conversion is done by Microsoft Team itself, so I have no impact on this.
