### ISSUE TITLE
Cant' access ui dashboard using ingress path /ui

### ISSUE THREAD

**Issue by samiamerni** [fjogeleit/policy-reporter#409]
hello,

I tried to use ingress to expose the policy report ui.

I was able to see the dashboard on / . But once I added the path /ui  the page keeps loading.

when I look to network I have:
Ui : 304 not modified
c53a56.js 404 not found

For information I'm using the helm chart policy-reporter-2.22.1
Is there a way to add root-path in the container ?

Thanks

**Comment by fjogeleit** [comment]
can you provide an example ingress config you use?

**Comment by samiamerni** [comment]
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-reporter-ui
spec:
  tls:
  - hosts:
      - k8s-a5cbbadc-dev.test
    secretName: montls-secret
  rules:
  - host: k8s-a5cbbadc-dev.test
    http:
      paths:
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: policy-report-ui
            port:
              number: 8080

**Comment by fjogeleit** [comment]
Ensure to set the required rewrite settings

https://kyverno.github.io/policy-reporter/guide/helm-chart-core#ingress-1

**Comment by samiamerni** [comment]
ui: 
   ingress:    
           enabled: true    
           annotations:      
               nginx.ingress.kubernetes.io/rewrite-target: /$1    
           hosts:      
              - host: domain.com        
                paths:        
                - path: "/ui/(.*)"

**Comment by samiamerni** [comment]
Thank you.

Issue resolved. Example in the previous comment.
