### ISSUE TITLE
[Bug] .Values.target.webhook.headers ignored in values.yaml (and maybe other values)

### ISSUE THREAD

**Issue by evgkrsk** [fjogeleit/policy-reporter#414]
Looking at https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/config.yaml I see that .Values.target.webhook.headers is not used there and effectively ignored. I assume that other similar problems may be present with other targets as well.

Maybe it is worth to migrate to directly write .Values.target in config.yaml via toYaml ?

**Comment by fjogeleit** [comment]
Hey, thanks for reporting, I'll take a look.

**Comment by fjogeleit** [comment]
I released a fixed version.

I am working on the 3.x release which will have a restructured configuration, so I kept it simple for now.
