### ISSUE TITLE
Download report html via api

### ISSUE THREAD

**Issue by alexandersperling** [fjogeleit/policy-reporter#425]
I'm recently looking more into the whole reporting mechanism of the policy report and was wondering if its possible to trigger a report generation and an report download via the API directly?

**Comment by fjogeleit** [comment]
Hey, right now there is no report generation directly in the Policy Reporter Core App, except the E-Mail HTML Reports.

The current v1 UI has a report download via the Kyverno Plugin.
The upcoming UI v2 will have a HTML Report Generation in the UI but in both cases its not possible to generate a report directly over the core API.

I could think about to provide the HTML Report content for the E-Mail Reports as API as well, if this would work for your use case.

**Comment by alexandersperling** [comment]
If there would be a possibility to some request das report content via API this would be sufficient I think. Thank you :)

**Comment by fjogeleit** [comment]
what kind of information do you need in the report?

You can check two example screens of the email reports here: https://kyverno.github.io/policy-reporter/core/email-reports

**Comment by alexandersperling** [comment]
the violations report would be the one I'm interested in

**Comment by fjogeleit** [comment]
I added a new API `/v1/html-report/violations` which renders the violations HTML report.

**Comment by fjogeleit** [comment]
I released the API with the latest helm chart
