### ISSUE TITLE
Policy Reporter no longer working after kyverno 1.11.0 upgrade

### ISSUE THREAD

**Issue by Shelby-Jiao** [fjogeleit/policy-reporter#430]
kyverno app version: 1.12.0
policy reporter chart version: 2.21.2

Policy Reports are now created on a per-resource basis and using a UID as the name rather than the previous behavior of per-policy. This may be a breaking change if you relied upon either of these attributes in previous versions. This change has the benefit of putting less pressure on the Kubernetes API server and less storage cost on etcd.
Meanwhile, policy reporter cannot get new policy reports name but only fetch report UID in prometheus metrics, as below
<img width="1468" alt="image" src="https://github.com/kyverno/policy-reporter/assets/99865457/79765593-7283-493f-b762-e5ac3f7aebf0">
<img width="1626" alt="image" src="https://github.com/kyverno/policy-reporter/assets/99865457/10bf08e8-be64-40fd-8c32-e332dcb7ee6e">
We may need to fetch name in owner reference or `scope.name`

**Comment by fjogeleit** [comment]
Hey, can you please try to upgrade to PolicyReporter >= v2.21.3

This version fixed an issue with resource mapping which leaded to empty resource values like name, kind, etc.

https://github.com/kyverno/policy-reporter/blob/main/CHANGELOG.md#2213

**Comment by Shelby-Jiao** [comment]
2.21.3 works, thanks!
