### ISSUE TITLE
[DOCS] The external-cluster section needs to mention that rest.enabled: true is required

### ISSUE THREAD

**Issue by rbjorklin** [fjogeleit/policy-reporter#434]
Hello!

Thanks for providing this excellent project! The section on [external-cluster](https://kyverno.github.io/policy-reporter/guide/helm-chart-core#external-clusters) needs to mention that this bit:
```yaml
rest:
  enabled: true
```

is required on all the external/target clusters.

**Comment by fjogeleit** [comment]
Thanks for pointing this out. Will adding this to the docs
