### ISSUE TITLE
Include the timestamp 

### ISSUE THREAD

**Issue by mveitas** [fjogeleit/policy-reporter#437]
When viewing the details of a policy result, it would be nice to know the timestamp associated with the result. We have had a number of people comment that they have added an exception to the policy and want to know if the data is stale

```
- category: Required
  message: 'validation error: The label `xxxx` is required. rule check-for-label-xxxx-owner
    failed at path /metadata/labels/xxxx/owner/'
  policy: require-xxx-labels
  result: fail
  rule: check-for-label-xxx-owner
  scored: true
  source: kyverno
  timestamp:
    nanos: 0
    seconds: 1715777711
```

**Comment by fjogeleit** [comment]
Where do you want to see the timesamp? In the UI / metrics?

**Comment by fjogeleit** [comment]
In general should the result switch from fail to skip after a policy exception is applied.

**Comment by mveitas** [comment]
Within the UI would be nice as part of the details if you drill into a particular result. I'd have to look at the newer UI design to make a suggestion of where this might be shown.

**Comment by fjogeleit** [comment]
okay, will take a look on it.

**Comment by fjogeleit** [comment]
Sorry for the delayed response, would something like work for you? The date formatting is based on the used browser language. de-DE in my case.

<img width="1459" alt="Bildschirmfoto 2024-07-28 um 13 23 52" src="https://github.com/user-attachments/assets/0d0912b4-9192-426d-bc8f-0095cb9cd4d7">

**Comment by mveitas** [comment]
That looks great!

**Comment by fjogeleit** [comment]
okay, thanks. will be released with the next preview build. Which will also be the first beta build

**Comment by fjogeleit** [comment]
Forgot to mention, its now available in the beta versions of the current preview release.
