### ISSUE TITLE
Question: Integration with Security Hub 

### ISSUE THREAD

**Issue by allamand** [fjogeleit/policy-reporter#468]
Hi, 

I've integrated policy-reporter with security Hub, and this works fine, thanks :)

 I have few questions:
- How to send only Fail report, I also have all Pass report that are send (in status Failed in SecurityHub).
- Can policy-reporter delete old report from securityhub that does not exist anymore in the cluster ? looks like it permanently send new report, but what happen to the older ones, that may be no more relevant ?

Thanks

**Comment by fjogeleit** [comment]
Hey, thanks for your feedback. 

To your questions:

1. You can set the minimumPriority to warning. This will only send fail results https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml#L659
2. The current stable version doesn’t support it. I currently working on v3 which support cleanup support for security hub. It’s currently in beta phase 
https://github.com/kyverno/policy-reporter/blob/3.x/charts/policy-reporter/values.yaml#L628

You can check the 3.x branch how to install it. If you have further question please reach out to me

**Comment by allamand** [comment]
@fjogeleit thanks for your response. I have difficulties to come back to the cluster to a specific report from SecurityHub, do you have example using : 

    # Added as additional properties to each securityHub event
    customFields: {}
    # filter results send by namespaces, policies and priorities
    filter: {}
    # add additional s3 channels with different configurations and filters
    channels: []

that can maybe used to add annotations like cluster-name to ease the retrieval of the information ?
I'll try the 3.x branch

**Comment by fjogeleit** [comment]
Hey @allamand 

The `customFields` adds static information to each result, e.g. the cluster name. In case of `SecurityHub` this details will be added to the Resource details.

So you can use it to add the cluster of the related resource:

```yaml
securityHub:
  customFields:
    cluster: "Dev Cluster 1"
```

**Comment by allamand** [comment]
@fjogeleit thanks, thats work fine. 
I am not able to filter events send using Kyverno resource filters like https://github.com/kyverno/kyverno/blob/main/charts/kyverno/values.yaml#L208, and I have results from kube-system or cloudwatch namespace that I would like to filter. What will be the best way to do it ? thanks

**Comment by fjogeleit** [comment]
Kyverno skips resourceFilters for backend scanning by default.

You can
1. Apply resourceFilters for background scans in Kyverno: https://github.com/kyverno/kyverno/blob/main/charts/kyverno/values.yaml#L624
2. Exclude these namespaces in the Policy Reporter reportFilter: https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml#L161

**Comment by allamand** [comment]
Hi @fjogeleit, thanks for all the responses. I managed to make it work as I wish, and know I would like to test the Beta but i'm failing to install it with ArgoCD: 

```
Failed to load target state: failed to generate manifest for source 2 of 2: rpc error: code = Unknown desc = `helm pull --destination /tmp/c8d85573-48a5-4afb-a544-c483473b77c2 --version 3.0.0-beta.7 --repo https://kyverno.github.io/policy-reporter policy-reporter/policy-reporter-preview` failed exit status 1: Error: chart "policy-reporter/policy-reporter-preview" version "3.0.0-beta.7" not found in https://kyverno.github.io/policy-reporter repository
```

seams the version is correctly present in the index.yaml though..

Edit: It works with valid chart name : `policy-reporter-preview`
