### ISSUE TITLE
Feature request: Support IAM role for service accounts for AWS Security Hub integration

### ISSUE THREAD

**Issue by rinaudjaws** [fjogeleit/policy-reporter#472]
Hello,

Would be great if the AWS Security Hub integration supports using AWS IAM service roles instead of static AWS access keys.

Related doc: https://eksctl.io/usage/iamserviceaccounts/

Regards,

**Comment by fjogeleit** [comment]
Hey, all AWS related services like S3, Kinesis and SecurityHub supporting Static Credentials, IRSA (Web- and Pod Identity) authentication.

The required env variables need to be set in the Pod
* WebIdentity: `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE`
* PodIdentity:  `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` and `AWS_CONTAINER_CREDENTIALS_FULL_URI`

**Comment by rinaudjaws** [comment]
Great, thanks a lot! It was not clear to me as the [doc](https://kyverno.github.io/policy-reporter/core/targets/) mentioned always `In case of AWS S3`. Thanks for the help! Closing the issue then

**Comment by fjogeleit** [comment]
yeah, will fix this. Thanks for mentioning
