### ISSUE TITLE
[Question] Beta Integration Security Hub cleanup

### ISSUE THREAD

**Issue by allamand** [fjogeleit/policy-reporter#475]
Hi, 

I was testing the beta version to see if insights could be cleaned up from securityHub when they are not still relevant (Pod did not exists anymore..) But I didn't managed to see how the clenup was working.

Also I like very much the new UI, seems that things are not finished (part of the UI is like  (but it's a beta so maybe this is normal).
Also I liked in actual version that I could see the Kyverno message on what to change to fix the issue, I didn't managed to see that in the new version:
![image](https://github.com/user-attachments/assets/a27bc052-a4b2-41fb-bc28-cec4dd45441b)

Thanks for all the work you are doing on this.

**Comment by fjogeleit** [comment]
Hey, thanks for your feedback. You can active security hub cleanups by setting this flag to true:

https://github.com/kyverno/policy-reporter/blob/3.x/charts/policy-reporter/values.yaml#L628

What parts of the ui seems to be not finished for you?

**Comment by fjogeleit** [comment]
To see the fail message you need to "open" an item by clicking the arrow on the very end of an item. I will see if I can improve this.

edit: I created a new preview release which recreated the old open on row click behavior in the result tables.

**Comment by allamand** [comment]
Thanks I activated the cleanup but not sure what that will do in SH ? The insights seams not changed in the console.

I’ll reinstall the beta and send you screenshot of the strange parts tomorrow.

‘do you have estimates date for v3 ?

**Comment by fjogeleit** [comment]
It should fetch active results associated with the updated PolicyReport and check if they are still active and if not set them to resolve.

https://github.com/kyverno/policy-reporter/blob/main/pkg/target/securityhub/securityhub.go#L108 is the related function. If it not works as expected let me know, then I will check again.

I plan the stable release end of sepetember

**Comment by allamand** [comment]
I don't see a consistent behaviour for pushing data so SH. I see difference between insights in SH and the ones send in the UI, which correctly reflect the changes in the cluster. If I add a vulnerability, I see it in the UI, and If I fix itIt is removed form the UI. for SH, I can see some of the insights, but not All the ones present in the UI.

I Tried to connect with you in CNCF slack

**Comment by allamand** [comment]
This is all working fine on latest Beta, thanks lot @fjogeleit for the hard work on this feature
