### ISSUE TITLE
Resources that don`t exist anymore in Kyverno Events tab

### ISSUE THREAD

**Issue by Pilotindream** [fjogeleit/policy-reporter#478]
Hello Community,

In my Policy Reporter UI in "Kyverno Events" tab I am able to see resources the do not exist anymore in my cluster:

![image](https://github.com/user-attachments/assets/b5f0d5e1-9cc0-4db0-9f4b-804520cfd809)

I thought that here will be visible only resources that currently exists in the cluster?
In "Kyverno" tab I see only resources that currently exists in the cluster, which I think is ok.

So I am wondering whether it is expected behavior?

Thanks in advance!

**Comment by fjogeleit** [comment]
As answered in https://github.com/kyverno/policy-reporter-ui/issues/400

Also this reports came from the Kyverno Plugin and not related to the core app, so closing this issue.
