### ISSUE TITLE
Webhook target configuration mismatch

### ISSUE THREAD

**Issue by DmitrievStepan** [fjogeleit/policy-reporter#528]
In current master both README and values.yaml shows that in webhook target you have to use `host` parameter, but actual chart uses `webhook` https://github.com/kyverno/policy-reporter/blob/39c354fd3f2c7cb66d844b9ee45c5ccdb065fe35/charts/policy-reporter/templates/_helpers.tpl#L181
Same goes for usetls and certificate there no indication in values or readme.

**Comment by fjogeleit** [comment]
Thanks, will take a look today

**Comment by fjogeleit** [comment]
Fixed with the latest RC release
