### ISSUE TITLE
Missing static manifests

### ISSUE THREAD

**Issue by oivindoh** [fjogeleit/policy-reporter#572]
In the [policy reporter documentation](https://kyverno.github.io/policy-reporter/guide/getting-started), there is mention of static manifests (initially added in https://github.com/kyverno/policy-reporter/pull/38), specifically links to these for the "Core + Policy Reporter UI + Kyverno Plugin" install:

- https://raw.githubusercontent.com/kyverno/policy-reporter/main/manifest/policy-reporter-kyverno-ui/namespace.yaml
- https://raw.githubusercontent.com/kyverno/policy-reporter/main/manifest/policy-reporter-kyverno-ui/config-secret.yaml
- https://raw.githubusercontent.com/kyverno/policy-reporter/main/manifest/policy-reporter-kyverno-ui/install.yaml

However, these files no longer exist in the repository.

I can't really find mention of why or when they were removed - would it make sense to generate these as artifacts in the pipeline as part of each release instead?

**Comment by fjogeleit** [comment]
Hey,

this documentation relates to Policy Reporter v2 (https://github.com/kyverno/policy-reporter/tree/2.x), so I missed to updated this links - sorry for that.

Main is the current RC release of Policy Reporter v3 which had major changes in the app and chart. So I decided to remove the current static manifests and renew them as I have a stable deployment for it.

But sounds like a good Idea to generate them as part of the CI/CD pipeline. Will take a look on that.
