### ISSUE TITLE
Bug: [v3] Elasticsearch target in _helpers.tpl missing typelessApi option

### ISSUE THREAD

**Issue by plinde** [fjogeleit/policy-reporter#595]
version tested: 3.0.0-rc.5

As part of policy-reporter v3, the `_helpers.tpl` section for Elasticsearch config is missing the option for `typelessApi`. 

https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/templates/_helpers.tpl#L162-L173

This causes policy-reporter to default to `typeless: false`, which breaks event ingestion in Elasticsearch 8.0+.

https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml#L387-L389

https://github.com/kyverno/policy-reporter/blob/main/pkg/target/elasticsearch/elasticsearch.go#L51-L58

`{"level":"error","ts":1732251727.9601336,"caller":"http/utils.go:50","msg":"Elasticsearch: PUSH FAILED","statusCode":400,"body":"{\"error\":\"no handler found for uri [/logs-kyverno-policy-reporter.log/event] and method [POST]\"}"`

**Comment by fjogeleit** [comment]
Thanks for your contribution, released in the latest RC release
