### ISSUE TITLE
Add policy-reporter chart to artifacthub

### ISSUE THREAD

**Issue by m-yosefpor** [fjogeleit/policy-reporter#82]
Adding policy-reporter helm chart to artifacthub same as what currently is for `kyverno` and `kyverno-policies` charts.

**Comment by fjogeleit** [comment]
Thanks for the suggestion, I will have a look on it.

**Comment by fjogeleit** [comment]
Hey, another user already added policy-reporter: https://artifacthub.io/packages/helm/policy-reporter/policy-reporter

So I'm not sure if we can add it again under the kyverno organization. Would this already help you?

**Comment by m-yosefpor** [comment]
@fjogeleit yes I've already seen this. But I think it would be great if we can have it under kyverno organization, and mark it as `Verified Publisher` and `Official`, so people can feel safe to use them. Also there are many packages for each application provided by many random users on artifacthub (search for example `prometheus` to see how many unofficial charts are there), but I think it is still possible to add it under kyverno organization as an official one.

Example for `Verified Publisher` and `Official`:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/47300215/138268705-c310ca84-1e3b-4d0e-9f8e-9353073ddefe.png">

**Comment by fjogeleit** [comment]
Okay, thanks for your feedback. I will reach out to Jim and ask him to add it.

**Comment by JimBugwadia** [comment]
Looks like its not possible to add the same repo multiple times:

![image](https://user-images.githubusercontent.com/5489990/138422640-56379b48-ef4c-4e94-b5d2-fc5460206e6f.png)

**Comment by fjogeleit** [comment]
Okay, thank you Jim.

**Comment by fjogeleit** [comment]
I asked in the Artifact Hub Slack for help, maybe its possible to move it or to ask the User to delete it.

**Comment by fjogeleit** [comment]
Its possible to claim the ownership: https://artifacthub.io/docs/topics/repositories/#ownership-claim I will try this today

**Comment by fjogeleit** [comment]
Done! :-)

https://artifacthub.io/packages/helm/policy-reporter/policy-reporter

**Comment by fjogeleit** [comment]
The verified publisher badge will be applied after the next release, when the Repo is processed again. After that I will create an issue to get a official status

**Comment by m-yosefpor** [comment]
great thank you both @fjogeleit @JimBugwadia

**Comment by fjogeleit** [comment]
Official Badge PR: https://github.com/artifacthub/hub/issues/1645
