### ISSUE TITLE
What is the purpose of this namespace value in the monitoring sub chart?

### ISSUE THREAD

**Issue by markussiebert** [fjogeleit/policy-reporter#92]
Just wonding what I can configure with this option, or what was the intention to configure a namespace in 2 places:

https://github.com/kyverno/policy-reporter/blob/bcd9e326f69520998a5d9b4facb6e19c98114556/charts/policy-reporter/charts/monitoring/values.yaml#L2

and then the online place it is referenced is here:

https://github.com/kyverno/policy-reporter/blob/bcd9e326f69520998a5d9b4facb6e19c98114556/charts/policy-reporter/charts/monitoring/templates/_helpers.tpl#L44-L51

So is this redundant to grafana.namespace setting? At the moment I dont understand it's purpose, so maybe I am using it wrong.

**Comment by fjogeleit** [comment]
Hey, thanks for your question. It's redundant. The `namespace` option was the initial one, with increasing configuration possibilities it was also added under Grafana. I'm working currently on a cleanup which will remove the namespace setting. It's still in for backward compatibility.

**Comment by fjogeleit** [comment]
If there is any question left feel free to reopen the issue
