### ISSUE TITLE
Feature Request: Provide config option to hide ClusterPolicy Reports in UI

### ISSUE THREAD

**Issue by windowsrefund** [fjogeleit/policy-reporter#94]
I don't generate any cpolr resources and am sure my users will end up clicking on ClusterPolicy Reports anyway :)

**Comment by fjogeleit** [comment]
Thanks for your request. I will have a look on it

**Comment by fjogeleit** [comment]
With the latest release you can disable each view as needed. See https://kyverno.github.io/policy-reporter/guide/04-helm-chart-core#configure-views for details.
