### ISSUE TITLE
Wrong image in default manifests for UI container

### ISSUE THREAD

**Issue by stephenrlouie** [fjogeleit/policy-reporter#98]
Possibly the same in other paths in the repo 

- https://github.com/kyverno/policy-reporter/blob/main/manifest/kyverno-policy-reporter-ui/install.yaml#L207
- https://github.com/kyverno/policy-reporter/blob/main/manifest/default-policy-reporter-ui/install.yaml#L96 (should this be 2.0.0?)

**Comment by fjogeleit** [comment]
Hey, the tags are right.

Policy Reporter Core released v2, UI and Kyverno Plugin have their own versions and reached v1. The latest version of the UI is 1.10.0 as you can check here:

https://github.com/orgs/kyverno/packages/container/package/policy-reporter-ui
https://github.com/orgs/kyverno/packages/container/package/policy-reporter-kyverno-plugin

**Comment by stephenrlouie** [comment]
@fjogeleit - the first link I posted uses your personal dockerhub container. should it move to the official release in ghcr?

**Comment by fjogeleit** [comment]
Oh that’s a good point. Thank you I will fix this asap
